js/package.json
js/src/provider/WalletLinkProvider.ts
js/src/provider/WalletLinkSdkUI.ts
js/src/provider/WalletLinkUI.ts
js/src/relay/WalletLinkRelay.ts
js/src/relay/WalletLinkRelayAbstract.ts

Make provider listen for chain id changed event and update its chain accordingly.

Update json rpc url and chain id at the same time

---

js/package.json

Bumps walletlink version to 2.2.10

Bump version to 2.2.10

---

js/src/WalletLink.ts
js/src/provider/WalletLinkProvider.ts

Add override to disable isCoinbaseWallet in walletlink provider options

Add override for `isCoinbaseWallet` in provider options

---

js/.eslintignore
js/.gitignore
js/package.json
js/src/provider/WalletLinkProvider.ts
js/src/relay/WalletLinkRelay.ts
js/src/relay/WalletLinkRelayAbstract.ts

* Add flexibility to handleAsyncMethods. Move making json rpc request into walletlink relay

Add `makeEthereumJSONRPCRequest` to WalletLinkRelay

---

js/src/relay/Web3Method.ts
js/src/relay/Web3Request.ts
js/src/relay/Web3Response.ts

* Add types to Web3Request and Web3Response

add web3 request/response types

---

js/src/init/events.ts
js/src/relay/WalletLinkRelay.ts

Add observability for issue tracking in walletlink relay

feat: Add observability to walletlink

---

js/package.json
js/src/components/LinkDialog.tsx
js/src/components/TryExtensionLinkDialog.tsx
js/src/version.ts

Adds a hidden tag with the walletlink version so its easier to diagnose issues that are due to a dapp being on an older walletlink version.

Add walletlink version tag

---

js/__tests__/addressStorage.test.js
js/package.json
js/src/init/events.ts
js/src/provider/WalletLinkProvider.ts
js/yarn.lock

Addresses https://github.com/walletlink/coinbase-wallet-sdk/issues/303
I believe `_addresses` is being mutated by the dapp
https://www.typescriptlang.org/play?ssl=10&ssc=27&pln=1&pc=1#code/DYUwLgBA+ghgJnATiAzi1EC8EDaAiABgA8ZSy8BdAKCoDMBXAOwGMwBLAe0YgHNwBBBMjSoAFAEoIAbyoQ5EZGHqJusIanQoqAXxoB6PRGYc4ICG0Yo2piHBgAHexAC29MDDAY1SDRhCMwRABPKlBIeB8RFCxeAXUoiSoI4U0cAgoYwiJ+HNy8KmNLDlAAOmAOHlFvFNQ0inEgA
```
let _addresses = ["0xaaaaaa"]
function getAddresses() {
return _addresses
}
// code inside dapp mutates _addresses entry
let addresses = getAddresses()
addresses[0] = "0xAAAAAA"
console.log(_addresses[0])
```

Guarantee lowercase addresses are compared

---

README.md

Add wagmi to list of libraries using Wallet SDK

Add wagmi library

---

src/relay/WalletSDKRelay.ts
webpack.config.js

- Fixes a bug wherein `requestEthereumAccount` callbacks were not properly invoked for legacy web3 calls

[bug] Fixes WalletSdkRelay callbacks

---

src/components/TryExtensionLinkDialog.scss
src/components/TryExtensionLinkDialog.tsx

- Updates text when user clicks on 'Install' -> Prompts user to connect again after clicking to refresh the page.
- Also opens mobile app download page in a new window

Install CoinbaseWallet dialog user response

---

src/components/TryExtensionLinkDialog.tsx

Fixes button behavior where clicking installation button should switch button functionality to refresh the page.

[chore] Fix button behavior

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/main.yml

- Updates github actions to run on `review_requested`
- Add PR template
- Updates issue templates with label & title

[chore] Update action trigger & add PR template

---

.github/workflows/versioning.yml

- Adding a github action to automatically update and tag version from input
- Related: https://github.com/coinbase/coinbase-wallet-sdk/pull/435
See: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
--

GitHub action: version + tag

---

.github/workflows/tagging.yml
.github/workflows/versioning.yml

- Update PR title
- Add commit message with tag version
- Fix conditional for tagging

[fix] Github action for PR creation & tagging

---

.github/workflows/codeql-analysis.yml

Added Code Scanning Github Actions Workflow with CodeQL to detect vulnerabilities. 
Code Scanning Docs: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning
Code Scanning ran on this PR and outputted some suggested changes

Add Code Scanning with CodeQL

---

src/util.test.ts

- adds unit tests for `util.ts` file
- tests

Unit tests: util file

---

src/CoinbaseWalletSDK.ts
src/provider/CoinbaseWalletProvider.ts

Add new flag for coinbase dapp browsers
Manually

Add new flag for coinbase dapp browsers

---

babel.config.js
jest.config.ts
package.json
src/components/TryExtensionLinkDialog.test.tsx
src/components/TryExtensionLinkDialog.tsx
yarn.lock

* Adds preact testing library
* Adds ui tests for TryExtensionLinkDialog

Add preact-testing-library and UI tests for TryExtensionLinkDialog

---

jest.config.ts
src/CoinbaseWalletSDK.ts
src/components/LinkFlow.test.tsx

[chore] LinkFlow test

---

jest.config.ts
jest.setup.ts
package.json
src/components/Snackbar.test.tsx
src/components/Snackbar.tsx
src/components/SnackbarContainer.test.tsx
yarn.lock

- Add tests to `Snackbar` component

[chore] Snackbar tests

---

src/connection/EventListener.ts
src/relay/WalletSDKRelay.ts

Remove origin from debugging events, cleanup unused events
Manually tested with coinbase wallet extension

Remove origin from debugging events, cleanup unused events

---

jest.setup.ts
package.json
src/components/Spinner.test.tsx
src/lib/ScopedLocalStorage.test.ts
src/provider/WalletSDKUI.test.ts
src/provider/WalletSDKUI.ts
src/relay/aes256gcm.test.ts
src/relay/aes256gcm.ts
yarn.lock

Adds unit tests for:
- components/Spinner
- lib/ScopedLocalStorage
- provider/WalletSDKUI
- relay/aes256gcm

[chore] Additional Tests

---

__tests__/addressStorage.test.js
__tests__/encryptDecrypt.test.js
src/CoinbaseWalletSDK.test.ts
src/CoinbaseWalletSDK.ts
src/__mocks__/provider.ts
src/__mocks__/relay.ts
src/provider/CoinbaseWalletProvider.test.ts
src/provider/CoinbaseWalletProvider.ts
src/relay/Web3Response.ts

Add initial tests for `CoinbaseWalletProvider`
w/ unit tests

First round of provider tests

---

package.json
scripts/prepublishOnly.sh
scripts/release.sh

Release script

---

jest.config.ts
src/__mocks__/relay.ts
src/fixtures/provider.ts
src/provider/CoinbaseWalletProvider.test.ts
src/provider/CoinbaseWalletProvider.ts

Add RPC method tests for CoinbaseWalletProvider
Unit tests

Add RPC method tests for CoinbaseWalletProvider

---

src/relay/WalletSDKRelay.ts
src/relay/WalletSDKRelayAbstract.ts

Allow session config to be exposed to users of WalletSDKRelay

expose session config

---

jest.config.ts
src/__mocks__/relay.ts
src/provider/CoinbaseWalletProvider.test.ts
src/provider/CoinbaseWalletProvider.ts

Add additional provider tests for watchAsset, addEthereumChain and switchEthereumChain
tests

Add more provider tests

---

src/CoinbaseWalletSDK.ts

Add conditional to prevent breaking reloadOnDisconnect

---

examples/native-sdk-android-client/app/build.gradle
examples/native-sdk-android-client/app/src/main/AndroidManifest.xml
examples/native-sdk-android-client/app/src/main/java/com/coinbase/android/beta/ActionsManager.kt
examples/native-sdk-android-client/app/src/main/java/com/coinbase/android/beta/MainActivity.kt
examples/native-sdk-android-client/app/src/main/res/layout/activity_main.xml
examples/native-sdk-android-client/app/src/main/res/values/colors.xml
examples/native-sdk-android-client/app/src/main/res/values/strings.xml
examples/native-sdk-android-client/build.gradle
packages/wallet-native-sdk/android/CoinbaseWalletNativeSDK/src/main/java/com/coinbase/android/nativesdk/message/request/Action.kt

Android WalletSDK Native Demo App improvements
What changed? Link to relevant issues.
* Now displays connected state
* ActionsManager to use mocked actions to send in either handshake or request
* Persists eth account info request processing
manually

Android WalletSDK Native Demo App improvements

---

examples/native-sdk-android-client/app/src/main/java/com/coinbase/android/beta/MainActivity.kt
examples/native-sdk-android-client/app/src/main/res/layout/activity_main.xml
examples/native-sdk-ios-client/SampleApp/ViewController.swift
packages/wallet-native-sdk/ios/CoinbaseWalletSDK/Message/Request/Web3JSONRPC.swift

updates Web3JSONRPC modeling for iOS with expected properties
What changed? Link to relevant issues.
-->
manually

updates Web3JSONRPC modeling for iOS with expected properties

---

README.md
packages/wallet-native-sdk/README.md

Add warning label to README.md to notify users NativeWalletSDK is WIP

Add warning label to README.md to notify users NativeWalletSDK is WIP

---

packages/wallet-native-sdk/android/CoinbaseWalletNativeSDK/src/main/java/com/coinbase/android/nativesdk/CoinbaseWalletSDK.kt
packages/wallet-native-sdk/android/CoinbaseWalletNativeSDK/src/main/java/com/coinbase/android/nativesdk/message/Message.kt
packages/wallet-native-sdk/ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
packages/wallet-native-sdk/ios/CoinbaseWalletSDK/Message/Message.swift

Add callbackUrl to all `Message` requests and handshake.
Manually

Add callbackUrl to all `Message` requests and handshake.

---

packages/wallet-sdk/src/provider/SolanaProvider.test.ts
packages/wallet-sdk/src/provider/SolanaProvider.ts

This PR adds support for an injected bridge to the SolanaProvider.
If the bridge is present, it sends messages over the bridge's `postMessage` function rather than `window.postMessage`
Additionally adds support for a `WEB3_RESPONSE` response type, which will come from sources other than the Extension.
- Manually
- Unit tests

Add bridge to SolanaProvider

---

packages/wallet-sdk/src/version.ts

update lib version

---

examples/native-sdk-ios-client/SampleApp/AppDelegate.swift
examples/native-sdk-ios-client/SampleApp/ViewController.swift
packages/wallet-native-sdk/ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
packages/wallet-native-sdk/ios/CoinbaseWalletSDK/Message/Request/Account.swift

iOS SDK - Provide Account / address on handshake response callback

---

packages/wallet-sdk/package.json

update wallet-sdk version

---

packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/provider/WalletSDKUI.ts
packages/wallet-sdk/src/provider/WalletUI.ts
packages/wallet-sdk/src/relay/WalletSDKRelay.ts
packages/wallet-sdk/src/relay/WalletSDKRelayAbstract.ts
packages/wallet-sdk/src/relay/Web3Request.ts

This PR will help in improving Network Switching, Below are the list of things that are changed.
- Switch chain according to dapp preference when the dapp gets connected for the first time
- Connected Address is passed to the content script when the switch ethereum chain is called as we will need address to modify chain in extension.
Tested manually on multiple dapps including prettier test dapp

[Extension-Standalone] Switch Chain on Account Request

---

packages/wallet-sdk/src/CoinbaseWalletSDK.ts
packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts

1. ledger connected extension wont switch network after establishing connection.
2. walletlink return right version number

ledger proof + return right version number

---

.github/workflows/tagging.yml

Additional guardrails for version tagging

Update github actions for tagging

---

.github/workflows/release-notes.yml
.github/workflows/tagging.yml

- Adds auto tagging & auto generation of release notes

Github actions: auto tag & auto generate release notes

---

.github/workflows/release-notes.yml

Set automated release notes as draft initially

Make initial release notes draft first

---

packages/wallet-sdk/package.json
packages/wallet-sdk/src/version.ts

[Manually Version update] v3.5.3

---

packages/wallet-sdk/src/provider/CoinbaseWalletProvider.test.ts
packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/provider/SolanaProvider.test.ts
packages/wallet-sdk/src/provider/SolanaProvider.ts

Updates check to ensure event origin matches location origin
manually

[WALL-12550]: Updates check to ensure event origin matches location origin

---

packages/wallet-sdk/package.json
packages/wallet-sdk/src/version.ts

v3.6.0-beta1

---

packages/wallet-sdk/package.json
packages/wallet-sdk/yarn.lock

upgrade vulnerable dependencies

---

.codeflow.yml

https://github.com/search?q=org%3Acoinbase+.codeflow.yml&type=code

[trivial] set up codeflow

---

examples/rainbowkit-demo/package-lock.json
examples/wagmi-demo/package-lock.json
examples/web3-onboard-demo/package-lock.json
examples/web3-react-demo/package-lock.json
examples/web3modal-demo/package-lock.json

address dependabot alerts

---

.github/workflows/notification.yml
.github/workflows/slack_template.txt

Notify new issues

---

.github/workflows/notification.yml
.github/workflows/slack_template.txt

notification template as env var

---

.github/workflows/notification.yml

[WALL-18868] Fix RCE issue on notification github action

---

.github/workflows/notification.yml

#trivial typo

---

packages/wallet-sdk/src/CoinbaseWalletSDK.ts
packages/wallet-sdk/src/index.ts

Update `ethereum` to `any`
From issue: https://github.com/coinbase/coinbase-wallet-sdk/issues/343

Update `ethereum` type to `any`

---

packages/wallet-sdk/src/errors.ts

Fix type inferrence issue

---

packages/wallet-sdk/src/errors.ts
packages/wallet-sdk/src/provider/WalletSDKUI.ts
packages/wallet-sdk/src/provider/WalletUI.ts
packages/wallet-sdk/src/relay/WalletSDKRelay.ts
packages/wallet-sdk/src/relay/WalletSDKRelayAbstract.ts

Add ErrorType and ErrorHandler types

---

packages/wallet-sdk/src/errors.ts

Fix circular dependency

---

packages/wallet-sdk/package.json
packages/wallet-sdk/src/provider/SubscriptionManager.ts
packages/wallet-sdk/yarn.lock

fix `dynamic require of "events/" is not supported` issue
[slack](https://coinbase.slack.com/archives/C034H9D313P/p1681880110146799)

Update eth-block-tracker version

---

README.md

Update copyright date in readme

Update copyright to 2023

---

packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/relay/MobileRelay.ts
packages/wallet-sdk/src/relay/Web3Response.ts

clarify return type of connectAndSign method

---

packages/wallet-sdk/src/mocks/relay.ts
packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/relay/MobileRelay.ts
packages/wallet-sdk/src/relay/WalletLinkRelay.ts
packages/wallet-sdk/src/relay/WalletSDKRelayAbstract.ts

connect and sign: assert environments

---

apps/testapp/package.json
apps/testapp/src/components/Layout.tsx
apps/testapp/src/components/RpcMethods/RpcMethodCard.tsx
apps/testapp/src/components/RpcMethods/index.ts
apps/testapp/src/context/CBWSDKProvider.tsx
apps/testapp/src/pages/_app.tsx
apps/testapp/src/pages/_document.tsx
apps/testapp/src/pages/index.tsx
apps/testapp/src/theme/index.ts
yarn.lock

* Add more to dev app testing env
* Update the dev app to have a few methods for testing. Will update as more testing is needed
Manually

Add ui to dev app

---

apps/testapp/src/components/RpcMethods/RpcMethodCard.tsx
apps/testapp/src/components/RpcMethods/index.ts
apps/testapp/src/context/CBWSDKProvider.tsx
packages/wallet-sdk/src/provider/MobileRelayUI.ts
packages/wallet-sdk/src/relay/MobileRelay.ts
packages/wallet-sdk/src/relay/WalletLinkRelay.ts

Sync master with v3.8 / Add personal_sign to test app

---

packages/wallet-sdk/package.json
packages/wallet-sdk/src/CoinbaseWalletSDK.ts
packages/wallet-sdk/src/provider/MobileRelayUI.ts
packages/wallet-sdk/src/relay/MobileRelay.ts
packages/wallet-sdk/src/version.ts

setUseLocationMethod

---

apps/testapp/src/components/RpcMethods/index.ts
packages/wallet-sdk/src/connection/WalletLinkConnection.ts
packages/wallet-sdk/src/relay/WalletLinkRelay.test.ts
packages/wallet-sdk/src/relay/WalletLinkRelay.ts

refactor WalletLinkRelay to remove RxJS dependencies
- manually
- new unit tests

[WALL-25366] refactor WalletLinkRelay to remove RxJS dependencies

---

packages/wallet-sdk/src/connection/RxWebSocket.test.ts
packages/wallet-sdk/src/connection/RxWebSocket.ts
packages/wallet-sdk/src/connection/WalletLinkConnection.ts
packages/wallet-sdk/src/relay/MobileRelay.ts
packages/wallet-sdk/src/relay/WalletLinkRelay.ts

5eb5e712a0426fec10a45475c6779cd2aa5da218
e6dac1d9274ca887abf03cfa8cb40df7364e121c

Sync check unseen events changes with master

---

packages/wallet-sdk/src/connection/WalletLinkConnection.ts
packages/wallet-sdk/src/relay/MobileRelay.ts

Encapsulate checkUnseenEvents() w/o exposing RxJS

---

.github/workflows/versioning.yml
packages/wallet-sdk/package.json
packages/wallet-sdk/src/version.ts

https://github.com/coinbase/coinbase-wallet-sdk/pull/999

fix versioning gh aciton

---

README.md
packages/wallet-sdk/README.md
packages/wallet-sdk/package.json
packages/wallet-sdk/src/version.ts
packages/wallet-sdk/tsconfig.build.json
scripts/release.sh

fix npm publish

---

packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts

- removed `supportsAddressSwitching` logic from sdk
- removed unused `isLedger` from sdk
- replaced duplicate code with existing func
Manually

Remove supportsAddressSwitching

---

packages/wallet-sdk/src/relay/aes256gcm.ts
packages/wallet-sdk/src/util.ts

Reverts coinbase/coinbase-wallet-sdk#956

Revert "ensure crypto api is referenced off of window object"

---

packages/wallet-sdk/src/connection/DiagnosticLogger.ts
packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts

https://coinbase.slack.com/archives/C03QN57NMHV/p1698264813994269

Add METHOD_NOT_IMPLEMENTED diagnostic event

---

packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts

added chainId to _prepareTransactionParams (#1043)

---

packages/wallet-sdk/package.json
packages/wallet-sdk/src/CoinbaseWalletSDK.ts
packages/wallet-sdk/src/constants.ts
packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/version.ts

We have already released 3.7.2 in Sept, but did not cp the changes to this v3.7 branch
This PP:
- cherry-picking the changes we released in 3.7.2
- bumping the current v3.7 branch version to 3.7.3-canary.0

Cherry-Picking 3.7.2 to v3.7

---

.github/workflows/build-and-deploy.yml
apps/testapp/package.json
apps/testapp/src/pages/index.tsx

Deploy SDK playground on every push to master

GitHub Action: Auto-Deploying master Branch to GitHub Pages

---

README.md
apps/testapp/src/components/Layout.tsx

Add links to TestApp and README

---

apps/testapp/package.json
package.json
yarn.lock

Move eth-sig-util dependency into testapp

---

apps/testapp/package.json
yarn.lock

Upgrade the sdk 3.9 off canary

playground to use 3.9.0

---

.github/workflows/build-and-deploy.yml
.github/workflows/main.yml

`git checkout ae895de54aa242eda39a11f8f205589256ad04a1 -- .github`

Revert github action changes

---

packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts

Update tests for `CoinbaseWalletProvider`
Changes are tests :)

update provider tests

---

packages/wallet-sdk/src/CoinbaseWalletSDK.ts

chainIds should be numbers

---

apps/testapp/src/context/CBWSDKReactContextProvider.tsx
apps/testapp/src/pages/index.tsx

Switch to use the new init config to set default chain in the testdapp

default chain logic in testdapp

---

apps/testapp/package.json
apps/testapp/src/components/Layout.tsx
apps/testapp/src/context/CBWSDKReactContextProvider.tsx
yarn.lock

SDK Version picker + SCW URL picker

SDK Playground - SDK Version picker + SCW URL picker

---

packages/wallet-sdk/src/core/type/ProviderInterface.ts

allow typing of request response

---

apps/testapp/README.md

minor changes to testapp readme
locally

testapp readme update

---

apps/testapp/src/components/RpcMethods/method/sendMethods.ts

Adding a data field so that we can pass arbitrary call data into the playground test app

[TRIVIAL] add data field to eth_sendTransaction in test app

---

packages/wallet-sdk/src/sign/walletlink/relay/connection/WalletLinkConnection.ts

fix a typo: `authentcate`->`authenticate`

chore: fix typos

---

packages/wallet-sdk/src/vendor-js/eth-eip712-util/index.js

chore: fix typo

---

packages/wallet-sdk/src/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/CoinbaseWalletSDK.ts
packages/wallet-sdk/src/core/type/ProviderInterface.ts
packages/wallet-sdk/src/core/util.ts
packages/wallet-sdk/src/sign/SignRequestHandler.ts

SignRequestHandler to take optional `keysUrl`, clean up constructor options

---

README.md
packages/wallet-sdk/docs/v4_with_wagmi.md

Add a guide for dapp development for Coinbase smart wallet with wagmi

---

README.md

- small changes to smart wallet description
- restore basic usage docs
markdown preview

restore basic usage docs

---

packages/wallet-sdk/src/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/core/constants.ts
packages/wallet-sdk/src/core/message/Action.ts
packages/wallet-sdk/src/sign/SignRequestHandler.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts

Route getCallsStatus to TPP

---

packages/wallet-sdk/docs/v4_with_wagmi.md

remove base from walkthrough since it's not supported yet

---

packages/wallet-sdk/src/rpcFetch/RPCFetchRequestHandler.ts

Adding Version into RPC call

---

packages/wallet-sdk/src/core/communicator/CrossDomainCommunicator.ts
packages/wallet-sdk/src/core/communicator/PopUpCommunicator.ts
packages/wallet-sdk/src/core/message/ConfigMessage.ts
packages/wallet-sdk/src/core/message/RPCMessage.ts
packages/wallet-sdk/src/core/message/index.ts
packages/wallet-sdk/src/sign/SignerConfigurator.test.ts
packages/wallet-sdk/src/sign/SignerConfigurator.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts

Move `request()` to parent

---

packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
packages/wallet-sdk/src/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/CoinbaseWalletSDK.test.ts
packages/wallet-sdk/src/CoinbaseWalletSDK.ts
packages/wallet-sdk/src/core/message/Action.ts
packages/wallet-sdk/src/core/type/ProviderInterface.ts
packages/wallet-sdk/src/sign/SignerConfigurator.test.ts
packages/wallet-sdk/src/sign/SignerConfigurator.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts
packages/wallet-sdk/src/sign/walletlink/WLSigner.ts

Clean up internal state management

---

packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
packages/wallet-sdk/src/CoinbaseWalletSDK.test.ts
packages/wallet-sdk/src/CoinbaseWalletSDK.ts
packages/wallet-sdk/src/core/type/ProviderInterface.ts
packages/wallet-sdk/src/sign/SignerConfigurator.test.ts

Redefine connection preference params

---

packages/wallet-sdk/src/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/sign/SignRequestHandler.ts
packages/wallet-sdk/src/sign/SignerConfigurator.test.ts
packages/wallet-sdk/src/sign/SignerConfigurator.ts
packages/wallet-sdk/src/sign/SignerInterface.ts
packages/wallet-sdk/src/sign/interface.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts
packages/wallet-sdk/src/sign/scw/SCWStateManager.ts
packages/wallet-sdk/src/sign/walletlink/WLSigner.ts
packages/wallet-sdk/src/sign/walletlink/relay/WLRelayAdapter.ts

#trivial consolidate interface files

---

apps/testapp/src/components/Layout.tsx
apps/testapp/src/context/CBWSDKReactContextProvider.tsx

dapp to choose preference

---

packages/wallet-sdk/src/core/communicator/PopUpCommunicator.ts
packages/wallet-sdk/src/core/message/ConfigMessage.ts
packages/wallet-sdk/src/sign/SignerConfigurator.ts
packages/wallet-sdk/src/sign/walletlink/WLSigner.ts

Handle WalletLinkSessionRequest initiated by popup

---

packages/wallet-sdk/src/CoinbaseWalletSDK.ts

chainIds too

---

packages/wallet-sdk/src/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/sign/SignRequestHandler.ts

cleanup SignRequestHandler

---

README.md
packages/wallet-sdk/docs/migration_guide.md

update migration guide details for new beta.10 interface
IDE markdown preview

migration readme updates for new interface

---

packages/wallet-sdk/docs/v4_with_wagmi.md

add steps, be explicit about beta.6 for now

---

packages/wallet-sdk/src/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/core/error/errors.ts
packages/wallet-sdk/src/sign/scw/SCWKeyManager.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts
packages/wallet-sdk/src/sign/scw/SCWStateManager.ts
packages/wallet-sdk/src/sign/walletlink/WLSigner.ts

#trivial clean up access control

---

packages/wallet-sdk/src/CoinbaseWalletProvider.ts

updateListener protected

---

packages/wallet-sdk/README.md

fix readme relative links

---

README.md

#trivial RC version on readme

---

docs/v4_with_wagmi.md

update quickstart guide to rc.1

---

docs/v4_with_wagmi.md

guide should use beta

---

docs/v4_with_wagmi.md

add detail about how to connect and connection status
markdown preview

add connection detail

---

apps/testapp/src/theme/index.ts

I made dark mode the default
locally

default test app to dark mode and system prefs

---

apps/testapp/src/theme/index.ts

lint theme config

---

apps/testapp/src/pages/index.tsx

side effect from removing beta7

---

docs/v4_with_wagmi.md

fix bad prop

---

docs/v4_with_wagmi.md

#doc fix typo

---

packages/wallet-sdk/src/sign/SignHandler.ts

Store signer type after successful handshake

---

packages/wallet-sdk/src/sign/SignHandler.test.ts

test for https://github.com/coinbase/coinbase-wallet-sdk/pull/1257

#trivial add tests for SignHandler.handshake

---

packages/wallet-sdk/src/core/communicator/KeysPopupCommunicator.ts

rejectPendingListeners

---

apps/testapp/src/context/CBWSDKReactContextProvider.tsx

Update Testdapp to switch URL correctly

---

.eslintignore
packages/wallet-sdk/src/core/type/util.ts
packages/wallet-sdk/src/sign/walletlink/relay/WLRelayAdapter.ts
packages/wallet-sdk/src/sign/walletlink/relay/WalletLinkRelay.ts
packages/wallet-sdk/src/sign/walletlink/relay/type/JSONRPC.ts
packages/wallet-sdk/src/sign/walletlink/relay/ui/RelayUI.ts
packages/wallet-sdk/src/sign/walletlink/relay/ui/WLMobileRelayUI.ts
packages/wallet-sdk/src/sign/walletlink/relay/ui/WalletLinkRelayUI.ts

`reloadOnDisconnect` used to be default to true
https://github.com/coinbase/coinbase-wallet-sdk/blob/4424c93ae31fb047cfafce41e157a03f8e55e887/packages/wallet-sdk/src/CoinbaseWalletSDK.ts#L77C1-L78C1
manual testing

#trival Handle WalletLink resetAndReload

---

README.md

Addresses https://github.com/coinbase/coinbase-wallet-sdk/issues/1254 
https://github.com/coinbase/coinbase-wallet-sdk/blob/fee35fa4e36df708c5295c212f21477166bef72f/packages/wallet-sdk/src/core/provider/interface.ts#L5-L8
& running locally

Correct provider.request reference in README

---

packages/wallet-sdk/src/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/core/communicator/Communicator.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts
packages/wallet-sdk/src/sign/util.test.ts
packages/wallet-sdk/src/sign/util.ts

trivial improvements for code quality from https://github.com/coinbase/coinbase-wallet-sdk/pull/1276
existing tests

#trivial clean up Communicator

---

packages/wallet-sdk/src/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/core/message/ConfigMessage.ts
packages/wallet-sdk/src/core/provider/interface.ts
packages/wallet-sdk/src/sign/interface.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts
packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts
packages/wallet-sdk/src/util/provider.test.ts
packages/wallet-sdk/src/util/provider.ts

- forward compatibility: add support for `extension` signer type
- cleanup
unit tests

Injected signer handling

---

apps/testapp/src/context/CBWSDKReactContextProvider.tsx

#trivial Playground: show WalletLink QR code with 3.x version

---

apps/testapp/src/components/RpcMethods/method/walletTxMethods.ts
packages/wallet-sdk/src/core/provider/method.ts

- adding support for `wallet_showCallsStatus`

[trivial] add wallet_showCallsStatus

---

packages/wallet-sdk/src/index.ts

https://github.com/wevm/wagmi/pull/3784

#trivial Export constructor parameter types

---

packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
packages/wallet-sdk/src/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/sign/util.ts

abstract signer creation 
existing tests

#trivial Separate out createSigner function

---

apps/testapp/package.json
apps/testapp/src/components/Layout.tsx
apps/testapp/src/context/CBWSDKReactContextProvider.tsx
yarn.lock

update playground to use 4.0.0 prod SDK
manually tested

#trivial update playground to use 4.0.0 prod SDK

---

README.md

Remove these beta and rc tags
automerge=true

remove beta & rc tags

---

apps/testapp/package.json
apps/testapp/src/components/Layout.tsx
apps/testapp/src/context/CBWSDKReactContextProvider.tsx
yarn.lock

update testapp to use v4.0.1

---

package.json
src/components/Layout.tsx
src/context/CBWSDKReactContextProvider.tsx
yarn.lock

reapplying @nateReiners 's PR https://github.com/coinbase/coinbase-wallet-sdk/pull/1300

#playground bump sdk version to 4.0.2

---

.github/workflows/build-and-deploy.yml

#trivial #playground auto deploy on push

---

package.json
src/components/Layout.tsx
src/context/CBWSDKReactContextProvider.tsx
yarn.lock

bump playground to 4.0.3

---

packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts

Adding Tests for SCWSigner
No code change

Adding Tests for SCWSigner

---

packages/wallet-sdk/src/core/communicator/Communicator.test.ts
packages/wallet-sdk/src/core/communicator/util.test.ts

Test for Communicator

---

README.md

checkout pg branch

---

packages/wallet-sdk/src/util/provider.ts

Helper to Get Provider from Top Frame

---

packages/wallet-sdk/src/util/provider.ts

style change

---

packages/wallet-sdk/.eslintrc.js

https://github.com/coinbase/coinbase-wallet-sdk/pull/1329

#trivial followup cleanup - lint check is expected to fail

---

packages/wallet-sdk/.eslintignore
packages/wallet-sdk/.eslintrc.js
packages/wallet-sdk/tsconfig.base.json
packages/wallet-sdk/tsconfig.build.json
packages/wallet-sdk/tsconfig.json

#trivial reenable linter & dedup tsconfig

---

package.json
src/components/Layout.tsx
src/context/CBWSDKReactContextProvider.tsx
yarn.lock

- Bumped playground to version 4.0.4

Bump playground to 4.0.4

---

packages/wallet-sdk/src/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/core/provider/interface.ts
packages/wallet-sdk/src/core/type/util.test.ts
packages/wallet-sdk/src/core/type/util.ts
packages/wallet-sdk/src/sign/extension/ExtensionSigner.ts
packages/wallet-sdk/src/sign/interface.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts
packages/wallet-sdk/src/sign/util.ts
packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.test.ts
packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts

- syntax clean up
- Reduce complexity around hexStringFromNumber and IntNumber casting
- prep for https://github.com/coinbase/coinbase-wallet-sdk/pull/1331

#trivial clean up & apply prettier changes

---

packages/wallet-sdk/src/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/core/message/RPCResponse.ts
packages/wallet-sdk/src/sign/extension/ExtensionSigner.test.ts
packages/wallet-sdk/src/sign/extension/ExtensionSigner.ts
packages/wallet-sdk/src/sign/interface.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts
packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.test.ts
packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts
packages/wallet-sdk/src/util/cipher.ts

- remove unnecessary generics from internal argument passing logic
- simplify function signatures where they are definitive via interface conformance
unit tests

#trivial Remove unnecessary generics

---

packages/wallet-sdk/android/build.gradle
packages/wallet-sdk/android/src/main/AndroidManifest.xml
packages/wallet-sdk/android/src/main/java/expo/modules/nativecommunicator/NativeCommunicatorModule.kt
packages/wallet-sdk/expo-module.config.json
packages/wallet-sdk/ios/NativeCommunicator.podspec
packages/wallet-sdk/ios/NativeCommunicatorModule.swift
packages/wallet-sdk/package.json
packages/wallet-sdk/src/core/native-communicator/NativeCommunicator.ts
packages/wallet-sdk/src/core/native-communicator/NativeCommunicatorModule.ts
packages/wallet-sdk/yarn.lock

Adding native communicator for sdk
- ios
- open/close safari tab
- response handler registeration
- android (OOS for this PR)
this communicator is not final

NativeCommunicator - iOS

---

packages/wallet-sdk/src/core/communicator/Communicator.native.test.ts
packages/wallet-sdk/src/core/communicator/Communicator.native.ts
packages/wallet-sdk/src/core/communicator/index.ts
packages/wallet-sdk/src/core/communicator/useInitCommunicator.native.tsx

Platform specific communicator, RN runtime will pick up the native communicator automatically

Platform specific communicator

---

packages/wallet-sdk/package.json
packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
packages/wallet-sdk/src/CoinbaseWalletSDK.native.test.ts
packages/wallet-sdk/src/CoinbaseWalletSDK.native.ts
packages/wallet-sdk/src/CoinbaseWalletSDK.test.ts
packages/wallet-sdk/src/core/communicator/Communicator.native.ts
packages/wallet-sdk/src/core/communicator/handleResponse.ts
packages/wallet-sdk/src/core/constants.ts
packages/wallet-sdk/src/core/message/RPCMessage.ts
packages/wallet-sdk/src/core/provider/interface.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts
packages/wallet-sdk/src/sign/util.native.test.ts
packages/wallet-sdk/src/sign/util.native.ts
packages/wallet-sdk/src/sign/util.test.ts
packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.test.ts

Hooking up cipher
manually + unit tests

RN to hook up Cipher in the flow

---

packages/wallet-sdk/src/core/communicator/Communicator.native.test.ts
packages/wallet-sdk/src/core/communicator/Communicator.native.ts
packages/wallet-sdk/src/core/communicator/handleResponse.ts

Update the handleResponse function signature for the native communicator to return a boolean
Unit tests

Update handleResponse function signature

---

packages/wallet-sdk/src/CoinbaseWalletSDK.test.ts
packages/wallet-sdk/src/CoinbaseWalletSDK.ts
packages/wallet-sdk/src/util/provider.test.ts
packages/wallet-sdk/src/util/provider.ts

revert back to v4.0.4 
previous unit tests have been revived.

Revert extension handling changes

---

packages/wallet-sdk/src/sign/scw/SCWSigner.ts
packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts
packages/wallet-sdk/src/util/provider.test.ts
packages/wallet-sdk/src/util/provider.ts

- addressing https://github.com/coinbase/coinbase-wallet-sdk/issues/1337
unit tests

Fix: fetchRPCRequest to return server errors

---

packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
packages/wallet-sdk/src/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/sign/interface.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts
packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.test.ts
packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts

Signer Cleanup Logic

---

packages/wallet-sdk/src/core/error/serialize.ts
packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts

- remove no-op checks
- remove unnecessary try-catch
- consolidate unauthorized error check

[WL cleanup] #trivial simplify error handling

---

packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts
packages/wallet-sdk/src/sign/walletlink/relay/WalletLinkRelay.test.ts
packages/wallet-sdk/src/sign/walletlink/relay/WalletLinkRelay.ts
packages/wallet-sdk/src/sign/walletlink/relay/mocks/relay.ts
packages/wallet-sdk/src/sign/walletlink/relay/type/EthereumTransactionParams.ts
packages/wallet-sdk/src/sign/walletlink/relay/type/Web3Method.ts
packages/wallet-sdk/src/sign/walletlink/relay/type/Web3Request.ts
packages/wallet-sdk/src/sign/walletlink/relay/type/Web3Response.ts

- simplify WalletLinkRelay constructor
- access control
- consolidate metadata
- remove redundant code
- deprecate unnecessary "generic" method type 
- simplify chainid
unit tests

[WL refactor] clean up Relay

---

package.json
src/components/RpcMethods/RpcMethodCard.tsx
src/components/RpcMethods/method/signMessageMethods.ts
src/components/RpcMethods/shortcut/multipleChainShortcuts.ts
src/pages/index.tsx
yarn.lock

Add ability to verify eip6492 messages.  This introduces using viem.
1. yarn dev
2. Connect an scw from keys.coinbase.com
3. Click example "personal sign" , verify that message verification is successful.

6492 verify message

---

src/components/RpcMethods/RpcMethodCard.tsx
src/components/RpcMethods/method/signMessageMethods.ts
src/components/RpcMethods/shortcut/multipleChainShortcuts.ts
src/pages/index.tsx

Playground Lint

---

packages/wallet-sdk/src/sign/walletlink/relay/WalletLinkRelay.ts

This PR adds the snackbar toast informing the user to confirm the request on their phone for Walletlink sessions that make a `switchEthereumChain` request.
We currently are not showing this toast, but the mobile phone must be opened in order for it to succeed.
Built the test dapp on the `playground` branch using the changes, confirmed that the toast displays

[Walletlink] Add snackbar toast for switchEthereumChain request

---

examples/testapp/src/components/MethodsSection/MethodsSection.tsx
examples/testapp/src/components/RpcMethods/RpcMethodCard.tsx
examples/testapp/src/components/SDKConfig/SDKConfig.tsx
examples/testapp/src/pages/config.tsx
examples/testapp/src/pages/index.tsx
packages/wallet-sdk/.eslintrc.js
packages/wallet-sdk/package.json
packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
packages/wallet-sdk/src/createCoinbaseWalletProvider.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.test.ts

Add testapp page for testing new config values
1. Start the dev server from the root. `yarn dev`
2. visit http://localhost:3001/config
3. Place a log inside the CoinbaseWalletProvider and verify the preferences are set.

Add testapp page for testing new config values

---

examples/testapp/config/headers.js
examples/testapp/next.config.js

Removing the next config. Builds were unable to find static assets
n/a

remove next config

---

.github/workflows/main.yml

Update test matrix (remove node 16 and 18)
https://nodejs.org/en/about/previous-releases
Unit Tests

Update test matrix (remove node 16 and 18)

---

packages/wallet-sdk/.eslintrc.js
packages/wallet-sdk/src/core/type/util.ts
packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts
packages/wallet-sdk/src/sign/walletlink/relay/WalletLinkRelay.ts
packages/wallet-sdk/src/sign/walletlink/relay/mocks/fixtures.ts
packages/wallet-sdk/src/vendor-js/eth-eip712-util/abi.js
packages/wallet-sdk/src/vendor-js/eth-eip712-util/util.js

- prefer Number.parseInt for clarity and modularity

[Trivial] use es6 namespaced Number.parseInt

---

examples/testapp/src/components/RpcMethods/RpcMethodCard.tsx

Fix lint in sdk playground
yarn lint

fix lint in playground

---

examples/testapp/src/context/CBWSDKReactContextProvider.tsx
packages/wallet-sdk/src/core/provider/interface.ts
packages/wallet-sdk/src/util/validatePreferences.ts

Expose keys dev: keys-dev.coinbase.com

expose keys-dev as a preference

---

examples/testapp/src/context/CBWSDKReactContextProvider.tsx

Improved connections in the playground.
Previously we had issues with changing keys url - with disconnects not being saved - with general flakiness around the connected state
Manually in the playground

Improve connection handling

---

examples/testapp/src/context/CBWSDKReactContextProvider.tsx

Fix disconnect in SDK playground
n/a

fix sdk playground disconnect

---

.github/workflows/main.yml
examples/testapp/src/components/RpcMethods/shortcut/signMessageShortcuts.ts

fix playground lint that is preventing deploys

---

packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
packages/wallet-sdk/src/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts

remove wallet_sign as its not finalized
Unit Tests

TRIVIAL - remove wallet_sign

---

packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
packages/wallet-sdk/src/core/type/index.ts
packages/wallet-sdk/src/core/type/util.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts
packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.test.ts
packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts
packages/wallet-sdk/src/sign/walletlink/relay/WalletLinkRelay.ts
packages/wallet-sdk/src/sign/walletlink/relay/mocks/relay.ts
packages/wallet-sdk/src/sign/walletlink/relay/type/EthereumTransactionParams.ts
packages/wallet-sdk/src/sign/walletlink/relay/type/Web3Request.ts
packages/wallet-sdk/src/sign/walletlink/relay/type/Web3Response.ts

Paves the way for future changes and cleans up old typing
n/a

Remove old type

---

packages/wallet-sdk/package.json
packages/wallet-sdk/src/stores/chain-clients/store.ts
packages/wallet-sdk/src/stores/chain-clients/utils.test.ts
packages/wallet-sdk/src/stores/chain-clients/utils.ts
packages/wallet-sdk/src/stores/sub-accounts/store.ts
packages/wallet-sdk/tsconfig.base.json
packages/wallet-sdk/vitest.config.ts
yarn.lock

This PR sets up stores for managing Linked Accounts
Nothing to test here. Just creates the new stores for sub account storage and clients for signing with sub accounts

Add Stores and Utils for Linked Accounts

---

examples/testapp/src/pages/add-address/components/Connect.tsx
packages/wallet-sdk/src/sign/scw/SCWSigner.ts

* Add account change event to addAddress prc
can test inside the example app
* Create a sub account
* Watch address update inside the connected flow

Add account change event

---

examples/testapp/src/pages/add-address/components/AddAddress.tsx
packages/wallet-sdk/src/core/rpc/wallet_addAddress.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts
packages/wallet-sdk/src/sign/scw/utils/createSubAccountSigner.test.ts
packages/wallet-sdk/src/stores/sub-accounts/store.ts

Update AddAddress based on recent spec changes
https://github.com/user-attachments/assets/2eced7c2-8f3d-4d36-aa3d-2ff9f4e460b7

Wallet Add Address Spec Changes

---

examples/testapp/src/components/RpcMethods/RpcMethodCard.tsx

This fixes the default "GrantPermission" method by recursively replacing any 'ADDR_TO_FILL' or 'YOUR_ADDRESS_HERE' strings
manually
https://github.com/user-attachments/assets/416c0992-ea2e-4ffb-9893-373421427ed7

Recursively replace address placeholders

---

examples/testapp/src/pages/add-address/components/AddAddress.tsx

Add version to the addAddress demo rpc call
Manually

fix demo params

---

packages/wallet-sdk/src/sign/scw/SCWSigner.ts
packages/wallet-sdk/src/sign/scw/utils/createSubAccountSigner.ts

This updates the sub account signer.
Manually

Add more rpc support for sub accounts

---

packages/wallet-sdk/src/stores/sub-accounts/utils.ts

Cleans up the original function and uses our standard error lib
Unit tests

clean up validation function

---

examples/testapp/src/components/RpcMethods/RpcMethodCard.tsx

Ugly fix, but doesn't hurt and this pattern is actually pretty common in real dapp

Fix for wallet_connect: only request account when needed

---

examples/testapp/src/pages/add-address/components/GrantSpendPermission.tsx
examples/testapp/src/pages/add-address/components/SpendPermissions.tsx
examples/testapp/src/pages/add-address/index.page.tsx

Add spend permissions to add address demo
Manually

Add spend permissions demo

---

examples/testapp/src/pages/add-address/components/SpendPermissions.tsx
examples/testapp/src/pages/add-address/index.page.tsx

make spend perms simple
Manually

make spend perms simple

---

examples/testapp/package.json
package.json
packages/wallet-sdk/package.json

Add a clean script to workspace
From root run:
```
yarn clean
```

add clean script

---

examples/testapp/src/pages/add-sub-account/components/AddOwner.tsx
examples/testapp/src/pages/add-sub-account/components/AddSubAccount.tsx
examples/testapp/src/pages/add-sub-account/components/Connect.tsx
examples/testapp/src/pages/add-sub-account/components/GenerateNewSigner.tsx
examples/testapp/src/pages/add-sub-account/components/GrantSpendPermission.tsx
examples/testapp/src/pages/add-sub-account/components/PersonalSign.tsx
examples/testapp/src/pages/add-sub-account/components/SendCalls.tsx
examples/testapp/src/pages/add-sub-account/components/SpendPermissions.tsx
examples/testapp/src/pages/add-sub-account/index.page.tsx

removes "customlogs: " from example app
n/a

fix logs in example app

---

.vscode/settings.json
examples/testapp/src/components/MethodsSection/MethodsSection.tsx
examples/testapp/src/context/CBWSDKReactContextProvider.tsx
examples/testapp/src/pages/_app.page.tsx
examples/testapp/src/pages/add-sub-account/components/AddOwner.tsx
examples/testapp/src/pages/add-sub-account/components/AddSubAccount.tsx
examples/testapp/src/pages/add-sub-account/components/Connect.tsx
examples/testapp/src/pages/add-sub-account/components/GenerateNewSigner.tsx
examples/testapp/src/pages/add-sub-account/components/GrantSpendPermission.tsx
examples/testapp/src/pages/add-sub-account/components/PersonalSign.tsx
examples/testapp/src/pages/add-sub-account/components/SendCalls.tsx
examples/testapp/src/pages/add-sub-account/components/SpendPermissions.tsx
examples/testapp/src/pages/add-sub-account/index.page.tsx
packages/wallet-sdk/src/core/error/errors.ts
packages/wallet-sdk/src/core/error/serialize.ts
packages/wallet-sdk/src/core/error/utils.ts
packages/wallet-sdk/src/sign/walletlink/relay/WalletLinkRelay.ts
packages/wallet-sdk/src/sign/walletlink/relay/connection/WalletLinkCipher.ts

format changes post biome update
n/a

format changes post biome update

---

packages/wallet-sdk/src/core/constants.ts

Fix typo in rpc.wallet.coinbase.com url
N/A

trivial: fix rpc url

---

.github/workflows/release.yml

Update the release script to run on any protected branch
n/a

update release prod script

---

packages/wallet-sdk/package.json
packages/wallet-sdk/src/sdk-info.ts

Version 4.3.2

---

CONTRIBUTING.md

docs: contribution guide

---

.github/actions/setup/action.yml
.github/workflows/release-canary.yml
.github/workflows/release.yml
examples/testapp/package.json
yarn.lock

Fix npm workspace issue preventing release actions from running
n/a

fix actions

---

.github/workflows/release-canary.yml
.github/workflows/release.yml

Fix release pipeline directory issues
n/a

fix directory issues

---

.github/workflows/release-canary.yml

Attempt to use workspace commands vs changing directories
From the CLI

update canary scripts to use workspace

---

.github/workflows/release.yml

Updates prod release action to match canary release
Tested via canary release action

Update prod release script

---

examples/testapp/src/pages/auto-sub-account/index.page.tsx
packages/wallet-sdk/src/core/error/errors.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts
packages/wallet-sdk/src/sign/scw/utils/createSubAccountSigner.ts

- fix: account ordering for `wallet_addSubAccount`
- feat: signer selector on /auto-sub-account page
- fix: convert errors thrown by viem to make them more readable
- fix: handle errors from other versions of viem

fix: canary patches

---

.github/workflows/release-canary.yml

Update the canary version to include time
n/a

Update the canary version to include time

---

packages/wallet-sdk/package.json
packages/wallet-sdk/src/sign/walletlink/relay/connection/HeartbeatWorker.js
packages/wallet-sdk/src/sign/walletlink/relay/connection/HeartbeatWorker.test.ts
packages/wallet-sdk/src/sign/walletlink/relay/connection/WalletLinkConnection.ts
packages/wallet-sdk/tsconfig.build.json

A new service worker was added in 4.3.3 for walletlink that broke consumer builds.
Run a build in the test app.

Fix builds in 4.3.3

---

packages/wallet-sdk/src/CoinbaseWalletProvider.ts
packages/wallet-sdk/src/core/telemetry/events/provider.ts
packages/wallet-sdk/src/core/telemetry/events/scw-sub-account.ts
packages/wallet-sdk/src/core/telemetry/events/snackbar.ts
packages/wallet-sdk/src/core/telemetry/logEvent.ts
packages/wallet-sdk/src/core/telemetry/utils.test.ts
packages/wallet-sdk/src/core/telemetry/utils.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts
packages/wallet-sdk/src/sign/scw/utils.ts
packages/wallet-sdk/src/sign/scw/utils/presentAddOwnerDialog.ts
packages/wallet-sdk/src/util/web.ts

* success rate
* snackbar usage

Sub Account Flow Telemetry

---

packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
packages/wallet-sdk/src/sign/scw/SCWSigner.ts

Linear: 
- Routes all `eth_requestAccounts` requests through `wallet_connect` and cache sub account results.
- Refactor `addSubAccount` function into existing `handleResponse`
Unit tests

fix: cache sub account in rpc calls

---

packages/wallet-sdk/src/CoinbaseWalletProvider.ts

Connection Issue
