- server/rpc/pub_sub.go
- server/rpc_test.go
- store/memory_store.go
1. The app crashes when unsubscribing while publishing a message to the unsubscribed channel because it sends a message in goroutine. https://github.com/walletlink/walletlink/blob/2.0.2/server/rpc/pub_sub.go#L124 ~~The fix is to wait for all subscribers to get a message, so safely unlock https://github.com/walletlink/walletlink/blob/2.0.2/server/rpc/pub_sub.go#L114 to unsubscribe~~ Created a lock for each subscriber and using it when publishing and unsubscribing
2. Fix tests (https://github.com/walletlink/walletlink/pull/1/commits/c69a594e8a8666283e5fbec3092fcb2a2ac40ad5). Failed because of https://github.com/walletlink/walletlink/commit/19dda19c607bcb8dfcc39ebb22508f8843424716#diff-588e74a11db2e82785409f89372885bf
> Fix not to crash when unsubscribing while publishing a message

- cmd/walletlinkd/walletlinkd.go
- config/config.go
- server/rpc.go
- server/server.go
Set read deadline to close idle connections to avoid `accept4: too many open files` errors
> Set read deadline for reading messages from websocket connection

- js/src/provider/WalletLinkProvider.ts
- js/src/util.ts
Per eth-sig-util (and verifying with Metamask), the sign typed data calls receive a stringified version of the input json message.
> Sign typed data calls receive a stringified version of the json message

- js/package.json
- js/src/provider/JSONRPC.ts
- js/src/provider/SubscriptionManager.ts
- js/src/provider/WalletLinkProvider.ts
- js/src/provider/Web3Provider.ts
- js/src/relay/WalletLinkRelay.ts
- js/src/vendor-js/qrcode-svg/index.d.ts
- js/tsconfig.json
- js/yarn.lock
Adds support for EIP-1193 provider methods
Also adds support for subscribing/unsubscribing to `newHeads` and `logs` events. `newPendingTransactions` and `syncing` are not supported.
Subscribe to a new event like so
```typescript
provider.request({ method: "eth_subscribe" params: ["newHeads"]})
```
The provider then emits new `message` events.
```typescript
provider.on("message", (data: ProviderMessage) => {})
```
Unsubscribe like so
```typescript
provider.request({ method: "eth_unsubscribe" params: ["<subscription id>"]})
```
> Add EIP-1193 support

- js/src/provider/WalletLinkProvider.ts
- js/src/provider/Web3Provider.ts
Remove the existing `ProviderError` class and replace the errors with ones from the `eth-rpc-errors` library
> Replace existing provider errors with errors from eth-rpc-errors

- js/compile-assets.js
**Description**
- Fixes https://github.com/walletlink/walletlink/issues/212
**Proposal**
SVGO's own `optimize` will not call their internal `encodeSVGDatauri` function until the min size has been reached, as seen here https://github.com/svg/svgo/blob/b37d90e12a87312bba87a6c52780884e6e595e23/lib/svgo.js#L57-L68
To fix this on our end we need to enable `multipass: true` while calling `optimize()` so it get's a chance to reach min size and thus call `encodeSVGDatauri`.
**Output with multipass: false (default)**
```ts
// Copyright (c) 2018-2021 WalletLink.org <https://www.walletlink.org/>
// Copyright (c) 2018-2021 Coinbase, Inc. <https://www.coinbase.com/>
// Licensed under the Apache License, version 2.0
export default `<svg width="16" height="16" fill="none" …
```
> fix(compile-assets): enable multipass + datauri inline

- .gitignore
- js/src/provider/WalletLinkProvider.ts
- js/src/relay/WalletLinkRelay.ts
- js/src/relay/WalletLinkRelayAbstract.ts
- js/src/relay/Web3Method.ts
- js/src/relay/Web3Request.ts
- js/src/relay/Web3Response.ts
TDD is in progress for this idea, and this PR can serve as a proof-of-concept until we reach alignment on the approach used here. 
We're adding this method so that 2 clients with an established walletlink connection can send messages across walletlink without walletlink needing to parse parameters on the message. This would be an optimization over the approach where we add a function type for each call.
1. Sending clients sends a message over walletlink conforming to whatever key:value parameters it needs
2. Receiving client is aware of the message type, in code referred to as "action" and can parse out the parameters.
3. Receiving client then sends back an equally ambiguous message that passes through walletlink in a similar way.
4. Sending client receives and parses the response object …
> Generic Messages over WalletLink

- js/package.json
- js/src/init/events.ts
- js/src/relay/WalletLinkRelay.ts
Fix bug where walletlink connection is dropped if we reconnected with 2 tabs open
Steps to reproduce:
1. Open a dapp in 2 tabs
2. Connect the mobile device
3. Disconnect dapp from mobile device
4. Reconnect the mobile device
5. Try to sign tx
Result: often the sign tx step will no longer work
Expected result: the sign tx step should work
Tested and fix verified using test dapp.
> Fix disconnect issue when 2 tabs are open

- js/package.json
- js/src/provider/WalletLinkProvider.ts
We had a check for this in cipher-webview's cipherprovider. Now that cipher-webview depends on walletlink, we need to have this check in WalletLinkProvider's addEthereumChain handling.
> Reject addEthereumChain request if it is for chainId the dapp is already on

- README.md
Have seen a few tickets such as https://github.com/walletlink/walletlink/issues/286 pop up where folks are confused about how to support networks other than eth mainnet using walletlink. This adds a section to the docs to explain how to best use Wallet for any evm-compatible network.
> Clarify EIP-3085 and EIP-3326 support in README

- js/src/provider/WalletLinkProvider.ts
- js/src/relay/Web3Response.ts
`AddEthereumChainResponse` and `SwitchEthereumChainResponse` had handling for two types of response that can come from the clients. New clients start rolling out on Monday February 7. It'll take 2-4 weeks for our next walletlink update to percolate to dapps, which is the amount of time needed for new clients to hit 99% adoption.
> Remove backwards compatibility code

- js/package.json
- js/src/relay/WalletLinkRelay.ts
There was a bug where we mark a session as in unlinked error state.  In the case where a session was established via the extension, the linked flag being false is a normal state.  The flag will remain false until the user opens the mobile app.
> Only mark session as in unlinked error state if it was linked previously

- src/relay/WalletLinkRelay.ts
#323 The current Deeplink jump loses hash and query params.
> fix: fix deeplink url

- README.md
Incorporate Cloud doc updates to README (where appropriate)
- Fix `ethereum.send` to `ethereum.request`
- Update text to match Cloud
- Expand install/upgrade section
- Update copyright year to 2022
- Rebrand WalletLink to Wallet SDK (in text, not code)
> Update readme to match cloud docs

- README.md
- package.json
- src/provider/JSONRPC.ts
- src/provider/WalletLinkProvider.ts
- src/provider/WalletLinkSdkUI.ts
- src/provider/WalletLinkUI.ts
- src/provider/Web3Provider.ts
- src/relay/WalletLinkRelay.ts
- src/relay/WalletLinkRelayAbstract.ts
- src/relay/Web3Method.ts
- src/relay/Web3Request.ts
- src/relay/Web3Response.ts
Today, one of the major uses of Ethereum wallets is to acquire and track assets. Currently, each wallet either needs to pre-load a list of approved assets, or users need to be stepped through a tedious process of adding an asset for their given wallet.
In the first case, wallets are burdened with both the security of managing this list, as well as the bandwidth of mass polling for known assets on their wallet.
In the second case, the user experience is terrible.
The [wallet_watchAsset](https://eips.ethereum.org/EIPS/eip-747) is a RPC method for allowing users to easily track new assets with a suggestion from sites they are visiting.
> feat: add wallet_watchAsset eht request support

- package.json
- src/provider/WalletLinkProvider.ts
- src/relay/WalletLinkRelay.ts
- src/relay/WalletLinkRelayAbstract.ts
First do an eip1102 as part of add ethereum chain if the wallet isn't yet authorized.
The current implementation will call relay.addEthereumChain even if the wallet isn't authed yet.  This only works in standalone (extension) mode.  If coinbase wallet sdk isn't connected to a mobile app yet or the extension isn't signed in yet, this will cause a snack bar to popup that leaves the user in a confusing state.  
Steps to reproduce:
1. With extension signed out and dapp not yet authorized
2. Call add ethereum chain 
Result: snack bar shows telling user to go verify a request on their mobile app
Fixed result: walletlink will ask user to authorize the dapp first.
> [Fix] Add ethereum chain should work if the user hasn't authed yet

- README.md
Update README by rebranding `walletlink` package to `@coinbase/wallet-sdk` and updating object/variable names in code snippets.
- Updated npm/yarn package name to `@conibase/wallet-sdk`
- Updated object and variable names to `coinbaseWallet` and `CoinbaseWallet`
- Removed walletlink.org link at bottom of README
- Did some minor copyediting
> Rebrand walletlink code snippets in README

- src/provider/CoinbaseWalletProvider.ts
- src/provider/WalletUI.ts
- src/relay/WalletSDKRelay.ts
- src/relay/WalletSDKRelayAbstract.ts
- src/relay/Web3Request.ts
For this first version of `watchAsset` feature, we're assuming that once users authorize wallet_watchAsset request, the token should be added in the current network. That said, we've decided to follow the approach of sending its current network chainId on the event params (cc @brendanww). 
It may be used by both extension and mobile apps to add token in the correct network
> Fix: Send dapps current network chainId through walletlink on wallet_watchAsset event

- __tests__/addressStorage.test.js
- package.json
- src/provider/CoinbaseWalletProvider.ts
Add option to disable switching selected address.  Currently the extension doesn't support this gracefully leading to timing issues if you connect a dapp to your mobile phone via the extension, and the mobile has a different address selected than the one the extension connected to originally.
> Disable address switch

- src/index.ts
- Prevent conflicting wallet providers for `window.ethereum`
> Update window.ethereum type to unknown

- .github/workflows/tagging.yml
- .github/workflows/versioning.yml
- Updates `versioning.yml` to create PR with version number
- Hit a snag with previous edit due to current settings 
- ![image](https://user-images.githubusercontent.com/50590950/162011895-42fb69f8-6d4d-4d87-aa35-1128188cd727.png)
- Revised to create a new PR instead, which would still involve manually merging to separately triggering tagging workflow
- Create `tagging.yml` to auto tag with version on master
| Github Action | Action Result |
| --- | --- |
|![image](https://user-images.githubusercontent.com/50590950/162009806-76a4bc3a-ab9f-45f5-a64d-79fd02eb874c.png)|  ![image](https://user-images.githubusercontent.com/50590950/162009683-b434b9e2-bd31-4e6b-ac83-17d824cb321b.png)|
- Note, was only able to verify for `tagging.yml`
> [chore] Workflow to create release PR & version tag

- .github/workflows/tagging.yml
- Fixes break in workflow due to git commit message appearing as:
```
v3.0.7 (#449)
Co-authored-by: erin-at-work <erin-at-work@users.noreply.github.com>
```
- use regex to only parse the version tag
locally
> [fix] Tagging through workflow

- src/CoinbaseWalletSDK.ts
- Add headless option to prevent onboarding flow display when user does not have extension installed
- Tested locally
> Add Headless Option to SDK for RainbowKit

- src/CoinbaseWalletSDK.ts
- src/relay/WalletSDKRelay.ts
Hey y'all, thanks for working on this project 👋 
We'd like to make the QR code URL available when running the SDK in headless mode. Currently there is an [early return in the `CoinbaseWalletSDK` constructor](https://github.com/coinbase/coinbase-wallet-sdk/blob/master/src/CoinbaseWalletSDK.ts#L98) that results in the QR code URL not being set when running in headless mode.
Since the inputs to `createQrUrl` are specific to the relay, it makes sense for the relay to expose it as a method. Users of `CoinbaseWalletSDK` will now be able to call `getQrUrl` and get back a URL whether or not they are running in headless mode!
Local test app
> fix: make qr code url available in headless mode

- src/CoinbaseWalletSDK.ts
- src/provider/CoinbaseWalletProvider.ts
- src/relay/WalletSDKRelay.ts
- Most third-party libraries expose the web3 provider as a connector for dev to integrate into their dapps. By adding the QR url directly onto the provider, makes it easier for devs to access on their frontend rather than accessing via our SDK method
locally
> Added QR URL on web3 provider

- src/provider/CoinbaseWalletProvider.ts
non-optional qrUrl made breaking change on extension, making the parameter optional.
> UPDATED: qrUrl on provider to be optional

- src/components/TryExtensionLinkDialog.scss
- src/components/TryExtensionLinkDialog.tsx
Added styles for loading spinner state in dark mode, and fix text color after clicking the install button.  Missed these in my last PR.
Tested with darkMode flag true, false, and omitted
> Fix missing styles in dark mode

- src/CoinbaseWalletSDK.ts
- src/provider/CoinbaseWalletProvider.test.ts
- src/provider/CoinbaseWalletProvider.ts
- src/provider/WalletSDKUI.ts
- src/provider/WalletUI.ts
- src/relay/WalletSDKRelay.ts
- src/relay/WalletSDKRelayAbstract.ts
- Added option on SDK to disable reloading dapp on disconnect
- Added feature to disable reload of page and emit "accountsChanged" event on disconnect (if option set true)
- Feature is optional due to lack of compatibility with existing dapps and aggregator libraries
locally with the following dapps: 
- Uniswap
- Compound
- Zapper
- Opensea
- Curve
- Sushiswap
- AAVE
- Balancer
- Prettier-Test-Dapp
> Add option on SDK to disable reloading dapp after disconnect

- src/provider/WalletUI.ts
- src/relay/WalletSDKRelay.ts
- Make breaking interface change on WalletUI optional for backward compatibility
locally
> Make setStandalone on WalletUI Optional

- packages/wallet-native-sdk/android/CoinbaseWalletNativeSDK/src/main/java/com/coinbase/android/nativesdk/CoinbaseWalletSDK.kt
- packages/wallet-native-sdk/android/CoinbaseWalletNativeSDK/src/main/java/com/coinbase/android/nativesdk/CoinbaseWalletSDKError.kt
- packages/wallet-native-sdk/android/CoinbaseWalletNativeSDK/src/main/java/com/coinbase/android/nativesdk/message/request/Web3JsonRPC.kt
- packages/wallet-native-sdk/ios/CoinbaseWalletSDK/CoinbaseWalletSDK.swift
- packages/wallet-native-sdk/ios/CoinbaseWalletSDK/Error.swift
- packages/wallet-native-sdk/ios/CoinbaseWalletSDK/Message/Message.swift
- packages/wallet-native-sdk/ios/CoinbaseWalletSDK/Message/Request/Web3JSONRPC.swift
Restricts handshake request to not include Sign/Send Tx methods
Handshake request should not be able to sign or send tx.  These actions only available post handshake.
What changed? Link to relevant issues.
manually
> Restricts handshake request to not include Sign/Send Tx methods

- packages/wallet-sdk/src/CoinbaseWalletSDK.test.ts
- packages/wallet-sdk/src/CoinbaseWalletSDK.ts
- packages/wallet-sdk/src/relay/WalletSDKRelay.ts
- packages/wallet-sdk/src/util.ts
* Coinbase DApp browser does not inject into iframes so grab CB browser's provider from top frame if it exists
* Support redirecting to CB Wallet's dapp browser when SDK is running in iframe
> Add support for Wallet SDK running in iframe in CB Dapp browser

- packages/wallet-sdk/src/provider/CoinbaseWalletProvider.test.ts
- packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts
Added handling for a WalletLinkMessage of type "addressChanged" which calls _setAddresses() with the provided address. This allows a consumer of the provider to change addresses on a dapp without the dapp needing to first request the address.
Manually tested and confirmed:
- Behavior related to initial connection to a dapp remains unchanged.
- Upon receiving the new "addressChanged" event, _setAddresses is called and the address is updated in the provider
- If the dapp supports the "accountsChanged" event, the address will immediately update on the dapp. If not, the page will need to be refreshed before the new address is visible.
> Handle addressChanged Event

- packages/wallet-sdk/package.json
- packages/wallet-sdk/src/provider/SolanaProvider.test.ts
- packages/wallet-sdk/src/provider/SolanaProvider.ts
This simplifies the Solana request being sent over the cipher bridge while leaving the extension request shape alone.
I also updated the `build:prod` script in `wallet-sdk` to include the README.md file from the outer package, as #639 broke it. 
- Manually
- Unit tests
> Update SolanaProvider for simpler cipher message passing

- packages/wallet-sdk/src/CoinbaseWalletSDK.ts
- packages/wallet-sdk/src/components/TryExtensionLinkDialog.tsx
- packages/wallet-sdk/src/relay/WalletSDKRelay.ts
- packages/wallet-sdk/src/util.test.ts
- packages/wallet-sdk/src/util.ts
Qrcode when extension is not installed had "1" as version number always. This PR will fix the url with the correct version number.
Manually
OLD URL: `https://www.walletlink.org/#/link?id=380e3ad1a9026379298001e8a00a86a2&secret=563db92b5[…]71bcd&server=https%3A%2F%2Fwww.walletlink.org&v=1&chainId=1`
NEW URL: `https://www.walletlink.org/#/link?id=380e3ad1a9026379298001e8a00a86a2&secret=563db92b5[…]71bcd&server=https%3A%2F%2Fwww.walletlink.org&v=3.5.1&chainId=1`
> FIx Version in URL for qrcode

- packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts
- In-app browser in Coinbase Wallet has its own logic for network switching, and it should always override the network to user chosen network when making web3 provider.
- thus, we dont need to switch network back to dapp's default after connecting.
manually tested
> [bug-fix] bring back network overriding for in-app broswer

- packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts
This PR will few bugs that were noticed after the release of network switching project release.
- Auto switch chain to previously used chain not working on Uniswap
- Not able to connect wallet to Etherscan when it uses Goerli
Tested manually on multiple dapps including prettier test dapp
> Fixed the issue of wrong chainID and jsonRpcUrl for provider

- packages/wallet-sdk/src/provider/SolanaProvider.ts
Moves the event origin check into the event listener callback. CB Wallet dapp browser calls the `handleResponse` function on the Solana provider directly without the `origin` and `source` fields.
Tested manually
> Move event origin check into event listener callback

- packages/wallet-sdk/src/relay/WalletSDKRelay.ts
- packages/wallet-sdk/src/relay/aes256gcm.test.ts
- packages/wallet-sdk/src/relay/aes256gcm.ts
> AES256GCM decrypt: replace Observable with Promise

- packages/wallet-sdk/src/relay/Session.ts
> Remove unused RxJS calls

- .codeflow.yml
- .github/workflows/notification.yml
- .github/workflows/slack_template.txt
> Notify new issues with permission check

- packages/wallet-sdk/src/relay/WalletSDKRelay.ts
Reset the `subscriptions` object in WalletSDKRelay - rxjs subscriptions class is not reusable.  This was manifesting as a dapp not being able to connect/send messages after reconnecting (for example beta.gem.xyz)
1. Connect coinbase wallet extension to mobile app
2. Go to beta.gem.xyz click Connect Wallet
3. Click cancel on the sign message prompt on mobile
4. Click connect wallet again
Before fix: Sign message prompt wouldn't appear on mobile
After fix: Sign message prompt appears on mobile.
> Reset subscriptions object, it's not reusable

- packages/wallet-sdk/src/CoinbaseWalletSDK.test.ts
- packages/wallet-sdk/src/CoinbaseWalletSDK.ts
- packages/wallet-sdk/src/connection/WalletLinkConnection.ts
- packages/wallet-sdk/src/relay/MobileRelay.ts
- packages/wallet-sdk/src/relay/WalletLinkRelay.ts
- packages/wallet-sdk/src/util.test.ts
- packages/wallet-sdk/src/util.ts
separate relay for mobile connection.
currently it subclasses existing relay, but will be updated later.
> MobileRelay

- packages/wallet-sdk/src/relay/WalletLinkRelay.ts
- packages/wallet-sdk/src/relay/Web3Method.ts
- packages/wallet-sdk/src/relay/Web3Request.ts
- packages/wallet-sdk/src/relay/Web3Response.ts
> Introduce connectAndSignIn

- packages/wallet-sdk/package.json
Previously, the generated version was wrapped in double quotes (used to created git diff) as opposed to single quotes which are standard in the codebase.
**version.ts**
Before: `export const LIB_VERSION = "3.7.1";`
After: `export const LIB_VERSION = '3.7.1';`
> fix: prebuild script

- packages/wallet-sdk/src/relay/aes256gcm.ts
- packages/wallet-sdk/src/util.ts
ensure crypto object is referenced off of window object.
Removing the need for the Crypto polly fill was originally addressed here (https://github.com/coinbase/coinbase-wallet-sdk/pull/144)
manually
> ensure crypto api is referenced off of window object

- packages/wallet-sdk/package.json
- yarn.lock
These dependencies were [previously used](https://github.com/coinbase/coinbase-wallet-sdk/pull/554/files) as polyfills in webpack bundle process but now that webpack is gone, they can be removed too.
`yarn test` succeeds and I confirmed they were not used in source code and only as part of webpack build [in the past](https://github.com/coinbase/coinbase-wallet-sdk/pull/554/files).
> remove: 2 unused dependencies

- packages/wallet-sdk/src/CoinbaseWalletSDK.ts
- packages/wallet-sdk/src/constants.ts
Resolves #874
TSC is used to compile release version of the library, which can't polyfill/substitute process.env object like Webpack.
This caused compilation error since process.env doesn't exist in the browser (unless substituted).
> fix: vite compatibility issue

- packages/wallet-sdk/package.json
- packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/provider/MobileRelayUI.ts
- packages/wallet-sdk/src/relay/MobileRelay.ts
- packages/wallet-sdk/src/relay/WalletLinkRelay.ts
Closes opened window after response is received from websocket or after timeout
https://github.com/coinbase/coinbase-wallet-sdk/assets/3137711/ca5836f0-58ab-4bcf-810f-0a4114165277
> Close opened window after response is received

- packages/wallet-sdk/package.json
Adds `"sideEffects": false` to package.json for maximum tree-shakability.
Without `"sideEffects"` switched off build systems aren't able to properly eliminate dead code (e.g. Next.js) and could still load the Coinbase Wallet SDK JS even if it's not used.
More info: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
> chore: add `sideEffects: false` to package.json

- packages/wallet-sdk/package.json
- packages/wallet-sdk/src/connection/RxWebSocket.test.ts
- packages/wallet-sdk/src/connection/RxWebSocket.ts
- packages/wallet-sdk/src/connection/WalletLinkConnection.ts
- packages/wallet-sdk/src/relay/MobileRelay.ts
- packages/wallet-sdk/src/relay/WalletLinkRelay.ts
- packages/wallet-sdk/src/version.ts
For mobile connections on iOS, sometimes Safari will kill the websocket connection in the background causing us to miss events. 
This hacky fix checks the `/events` endpoint for unseen events and merges it into the incoming events observable. Also needed to add some logic to re-connect the RxWebsocket connection instead of throwing an error when `sendData` is called while the websocket is connected. From testing, this seems to work fairly reliably, but a more robust solution would be better in the long term.
> Check unseen events after navigating back to browser

- packages/wallet-sdk/src/provider/SolanaProvider.test.ts
- packages/wallet-sdk/src/provider/SolanaProvider.ts
Security request to remove postMessage wildcard in favor of window.origin
Manually in cipher and react native
> Update postmessage targetOrigin to window.origin

- packages/wallet-sdk/package.json
- packages/wallet-sdk/src/CoinbaseWalletSDK.test.ts
- packages/wallet-sdk/src/relay/WalletLinkRelay.ts
- yarn.lock
> remove bind-decorator dependency

- packages/wallet-sdk/src/components/LinkFlow/LinkFlow.test.tsx
- packages/wallet-sdk/src/components/LinkFlow/LinkFlow.tsx
- packages/wallet-sdk/src/provider/WalletLinkRelayUI.test.ts
- packages/wallet-sdk/src/provider/WalletLinkRelayUI.ts
- packages/wallet-sdk/src/provider/WalletUI.ts
- packages/wallet-sdk/src/relay/WalletLinkRelay.ts
- removed connected and chainId from WalletUIOptions interface, and moved it 1 level down to LinkFlow
- changed publishEvent to protected
Manually
> Small Refactor

- packages/wallet-sdk/src/connection/WalletLinkConnection.ts
- packages/wallet-sdk/src/connection/WalletLinkWebSocket.ts
- packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts
> Fix: clean up listeners on disconnection / diagnostic log only when it fails

- packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts
Adding parsing for chainId in SendTx
> Parsing ChainId in SendTx

- packages/wallet-sdk/src/provider/CoinbaseWalletProvider.test.ts
- packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts
CoinbaseWalletProvider should NOT listen to 'addressChanged' event 
Unit tests
> CoinbaseWalletProvider should NOT listen to 'addressChanged' event

- .codeflow.yml
- packages/wallet-sdk/package.json
- packages/wallet-sdk/src/relay/walletlink/ui/components/Snackbar/Snackbar.tsx
- scripts/deploy.yml
- scripts/publish-canary.Dockerfile
- scripts/release.sh
- tsconfig.base.json
> Define codeflow job

- apps/testapp/src/components/RpcMethods/method/RpcRequestInput.ts
- apps/testapp/src/context/CBWSDKProvider.tsx
- packages/wallet-sdk/src/relay/walletlink/type/Web3Method.ts
- packages/wallet-sdk/src/relay/walletlink/type/Web3Request.ts
> Misc update

- packages/wallet-sdk/src/relay/mobile/MobileRelay.ts
- packages/wallet-sdk/src/relay/mobile/MobileRelayUI.ts
Navigating to CB Wallet app deeplink via window.open and not replacing window.href was causing a broken behavior when the SDK is running from inside a webview. This PR replaces the redirecting strategy in order to fix this bug
Manually tested using an RN test app that renders the test dapp from inside a webview
| Before | After |
| -- | -- |
| <video src="https://github.com/coinbase/coinbase-wallet-sdk/assets/26755665/fc52ee2e-72c7-42a5-8889-a9340fe2b418" /> | <video src="https://github.com/coinbase/coinbase-wallet-sdk/assets/26755665/48e08521-0419-41f8-8f37-48ca8294575a" /> |
> fix redirecting on webviews

- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/sign/scw/SCWStateManager.test.ts
- packages/wallet-sdk/src/sign/scw/SCWStateManager.ts
We follow the app's `chainIds` param to set the default network for SDK, but we missed out SCWStateManager, so it's always sending requests on mainnet. This PR updated SCWStateManager to take `chainIds` for fallback
Manually
> initialize SCWStateManager with dapp chainIds

- apps/testapp/src/components/Layout.tsx
- apps/testapp/src/context/CBWSDKReactContextProvider.tsx
- packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/CoinbaseWalletSDK.test.ts
- packages/wallet-sdk/src/CoinbaseWalletSDK.ts
- packages/wallet-sdk/src/core/communicator/ConnectionPreference.ts
- packages/wallet-sdk/src/index.ts
- packages/wallet-sdk/src/sign/SignRequestHandler.ts
- packages/wallet-sdk/src/sign/scw/transport/PopUpCommunicator.ts
- This PR replaces the `connectionPreference?: ConnectionPreference` SDK Option with a simpler `smartWalletOnly?: boolean`
- reduces mental overhead for dapp developers compared to connectionPreference enum
- gives dapp developers and easy way to hide wallet link if desired
locally 
unit tests
> Replace connectionPreference: enum with smartWalletOnly: boolean

- packages/wallet-sdk/src/sign/SignerConfigurator.ts
initSigner relies on chainIds to default to dapp's preferred chainIds, need to assign chainIds before initSigner
> chainIds before initSigner

- apps/testapp/src/components/RpcMethods/method/walletTxMethods.ts
- apps/testapp/src/components/RpcMethods/shortcut/walletTxShortcuts.ts
- packages/wallet-sdk/src/sign/SignRequestHandler.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/sign/scw/SCWStateManager.ts
- packages/wallet-sdk/src/sign/scw/message/type/Action.ts
- packages/wallet-sdk/src/sign/scw/message/type/Response.ts
Updates to params and method names based on changes here: https://github.com/ethereum/EIPs/pull/8361 
- rename `wallet_sendTransaction` to `wallet_sendCalls` 
- old params:
``` 
{
chainId: string;
sender: string;
version: string;
gas?: string;
calls: {
target: string;
value: string;
data: string;
}[];
capabilities: object;
};
```
- new params:
```
{
version: string;
chainId: `0x${string}`; // Hex chain id
from: `0x${string}`;
calls: {
to: `0x${string}`;
data: `0x${string}`;
value: `0x${string}`; // Hex value
}[];
capabilities: Record<string, unknown>;
};
``` 
- rename `wallet_getTransactionStatus` to `wallet_getCallsStatus`
- strengthen typing of wallet capabilities
- old: `_walletCapabilities?: Record<string, object>;`
- new: `_walletCapabilities?: Record<`0x${string}`, Record<string, …
> EIP-5792 Updates

- packages/wallet-sdk/package.json
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/version.ts
changed backend handling so we just return the json rpc result. this brings the behavior in line with how wallets (popup, extension) respond to json rpc requests. ie they respond by excluding json rpc request id and version, and just return the result.
> [trivial] Return JSON-RPC result from backend

- packages/wallet-sdk/src/sign/walletlink/relay/WalletLinkRelay.ts
Certain consumers are seeing inconsistent results when navigating to the wallet from a mobile browser to establish a walletlink connection. This applies specifically to the configuration where the dapp does not want to route the user to the in-app "dapp browser".
The change is to ensure the blur listener event is set before the app hits the blur event.
In the future we could look at checking for unseen events any time we re-establish the websocket, or even every time we refocus on the app. That would be even better - and this is just a small step in the right direction that should improve how reliably this code executes.
Change is straightforward and trivial enough - totally untested - just moved a bit of code up in the sequence of a file. Any help sanity checking this is appreciated.
> Setup blur and focus events prior to navigating

- packages/wallet-sdk/src/sign/SignerConfigurator.ts
- packages/wallet-sdk/src/sign/scw/transport/PopUpCommunicator.ts
- packages/wallet-sdk/src/sign/scw/transport/PopUpConfigurator.ts
1. SDK Pass Version on Handshake
2. When user close popup before selecting the signer, SDK can now correctly handling it and throw back to dapp
> SDK Pass Version on Handshake + Error Handling for Signer Selection

- apps/testapp/src/context/CBWSDKReactContextProvider.tsx
- apps/testapp/src/pages/index.tsx
- packages/wallet-sdk/src/CoinbaseWalletSDK.test.ts
- packages/wallet-sdk/src/CoinbaseWalletSDK.ts
- packages/wallet-sdk/src/index.ts
- packages/wallet-sdk/src/sign/SignerConfigurator.test.ts
- packages/wallet-sdk/src/sign/SignerConfigurator.ts
- packages/wallet-sdk/src/sign/scw/transport/ConfigMessage.ts
- packages/wallet-sdk/src/sign/scw/transport/PopUpCommunicator.ts
- only return injected provider, when coinbaseWalletExtension is injected and coinbaseWalletExtensionSigner is not
- when FE returns selected signer as extension, grab the injected coinbaseWalletExtensionSigner
- sends coinbaseWalletExtensionSigner status to FE for selection
When extensionSigner is injected, always open SCW popup and show extension option
https://github.com/coinbase/coinbase-wallet-sdk/assets/22125939/16e27720-6e8d-4a78-b698-36305e6e04af
when extensionSigner is not injected, but old extension provider is injected
https://github.com/coinbase/coinbase-wallet-sdk/assets/22125939/c0050356-4afa-409e-a016-cb0fe81c0be6
When error grabbing injected extensionSigner, reset everything
https://github.com/coinbase/coinbase-wallet-sdk/assets/22125939/455d5fd6-afb0-4579-83f0-b4c1cb781fdd …
> Extension Detection

- packages/wallet-sdk/src/CoinbaseWalletSDK.test.ts
- packages/wallet-sdk/src/CoinbaseWalletSDK.ts
- packages/wallet-sdk/src/core/type/ProviderInterface.ts
- remove `sdk.disconnect()` method
- add disconnect to `ProviderInterface` otherwise TS complains if anyone tries to call provider.disconnect [like this example in wagmi](https://github.com/wevm/wagmi/pull/3784/files/8c213576b671b1c7b033f2f9e1188bcbd5068f82#diff-b05598fc1a520e04372175e02a71b5110937ac12bb448dd939b163f5ad8ee463R65)
- on the extension side, `ExtensionCoinbaseWalletProvider extends CoinbaseWalletProvider` so disconnect can be called now with v3 and also when the extension upgrades to SDK v4
locally
> disconnect cleanup

- packages/wallet-sdk/src/rpcFetch/RPCFetchRequestHandler.ts
The `RPCFetchRequestHandler` class was returning the entire json rpc envelope instead of just the result (see previous implementation from [3.9.1](https://github.com/coinbase/coinbase-wallet-sdk/blob/v3.9.1/packages/wallet-sdk/src/provider/CoinbaseWalletProvider.ts#L519)).  This breaks compatibility with dapps.  Instead it should return the result.
> Parse result rather than returning entire json rpc envelope

- README.md
Link to (updated) scw setup steps in cloud docs
Remove Basic Usage section which was all moved to cloud docs 
vscode markdown preview
> update docs, dedup basic usage steps, link to cloud docs

- apps/testapp/src/pages/index.tsx
- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
fixes the testapp which was using a nonstandard getter which sdk v4 no longer supports
locally
> make testapp listen for chainChanged event to avoid using a getter

- README.md
The link to the public documentation website was incorrect. The previous link resulted in a 404. This change updates the link to point to the most recent developer documentation start page for the wallet SDK.
> Fix broken link to the public developer docs

- packages/wallet-sdk/src/CoinbaseWalletSDK.test.ts
- packages/wallet-sdk/src/CoinbaseWalletSDK.ts
- packages/wallet-sdk/src/util/provider.test.ts
- packages/wallet-sdk/src/util/provider.ts
appName and appLogoUrl can be empty string. Updated handling to make that also defaulting to 'Dapp' and getFavicon()
> #fix appName can be empty string

- packages/wallet-sdk/src/core/communicator/CrossDomainCommunicator.ts
- packages/wallet-sdk/src/core/communicator/PopUpCommunicator.ts
- packages/wallet-sdk/src/core/message/Message.ts
- packages/wallet-sdk/src/sign/SignHandler.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/sign/walletlink/WLSigner.ts
> #trivial Clean up cross domain communicator

- apps/testapp/src/context/CBWSDKReactContextProvider.tsx
This PR adds keys-beta.coinbase.com/connect as an option for developers to test against.
Verified locally by setting it and opening up a eth_requestAccounts
> Add keys-beta.coinbase.com/connect to playground

- packages/wallet-sdk/src/sign/util.ts
`catch(() => {})` does not block the rest of the function, we should catch the 'error' (FE not requesting walletlink URL) at one level higher at `fetchSignerType`
Manually
> Fix Extra Popup After Handshake

- packages/wallet-sdk/src/core/communicator/Communicator.test.ts
- packages/wallet-sdk/src/core/communicator/Communicator.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/sign/util.ts
- Safari was blocking the popup from opening whenever a request was sent. This is because the request message is being constructed before the popup is opened in `SCWSigner`. Safari blocks it because it is not opened immediately after a button is clicked.
- This PR updates the `request` method so that it first opens the popup and then constructs the request. This is how it was done before [this PR](https://github.com/coinbase/coinbase-wallet-sdk/pull/1260)
- Manually:
| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/coinbase/coinbase-wallet-sdk/assets/16995513/619d30b6-ca27-4401-b979-a462a2935a0a">  | <video src="https://github.com/coinbase/coinbase-wallet-sdk/assets/16995513/bf69b157-c3d6-41d9-81fa-cee43cc02b35">|
> Fix popup blocked on Safari

- apps/testapp/src/components/RpcMethods/shortcut/sendShortcuts.ts
dapps are blocked from calling directly to the smart wallet's address
> Fix playground example send: don't send to wallets own address 

- packages/wallet-sdk/src/core/communicator/Communicator.test.ts
- packages/wallet-sdk/src/core/communicator/Communicator.ts
- There's an issue on iPads where the object returned from `window.open` stays defined even after the window/tab is closed. This causes the popup to not be opened when one was opened in the past due to this line of code:
https://github.com/coinbase/coinbase-wallet-sdk/blob/53f37742c40ff5c20f6c652611b322c318332328/packages/wallet-sdk/src/core/communicator/Communicator.ts#L82-L83
- To solve this, I added a check for `popup.closed` on the same line, so that the popup is opened again when it's closed
- Manually and unit tests
- Also verified that it's still working as expected on other devices
| Before  | After |
| ------------- | ------------- |
| <video src="https://github.com/coinbase/coinbase-wallet-sdk/assets/16995513/f1043bb0-79c9-4c22-b45c-1d846c6f5db7">  | <video …
> Fix popup not opening on iPad

- packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
Make `eth_chainId` match the spec. It should return a hex string.
https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_chainid
> make eth_chainId comply with spec

- packages/wallet-sdk/src/core/communicator/Communicator.test.ts
- packages/wallet-sdk/src/core/communicator/Communicator.ts
- It's possible for a user to leave the popup open between requests, especially after onboarding when the popup is not closed programmatically. Because of this, when a new request comes through, the popup doesn't re-focus itself and updates in the background. This leads to a bad UX since the user can't see the popup and has to manually re open it.
- This PR simply calls `popup.focus()` every time a new request comes to an already open popup. This ensures that the popup doesn't stay hidden in the background when a user performs an action on a dapp
- Manually and unit tests
https://github.com/coinbase/coinbase-wallet-sdk/assets/16995513/47df2600-d3e0-4864-bd5c-c3918473838a
https://github.com/coinbase/coinbase-wallet-sdk/assets/16995513/7e738c17-869f-43aa-8088-083ffe2cf1c7
> Re-focus the popup between requests

- packages/wallet-sdk/src/util/provider.test.ts
- packages/wallet-sdk/src/util/provider.ts
window.top may throw DOMException, we should not let this error blocking us from continuing
> Don't throw when grabbing injected provider

- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/util/provider.test.ts
- packages/wallet-sdk/src/util/provider.ts
separating out from https://github.com/coinbase/coinbase-wallet-sdk/pull/1331
existing tests
> #trivial remove unnecessary catch / throw

- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/sign/interface.ts
- packages/wallet-sdk/src/sign/scw/SCWStateManager.test.ts
- packages/wallet-sdk/src/sign/scw/SCWStateManager.ts
- packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts
separating out from https://github.com/coinbase/coinbase-wallet-sdk/pull/1331
unit tests
> #trivial remove `updateSource` from updateListener

- packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/core/error/serialize.test.ts
- packages/wallet-sdk/src/core/error/serialize.ts
- packages/wallet-sdk/src/util/provider.ts
- Fix missing error serialization
- Fix request arg type check
- Remove unnecessary `method` parsing on `serializeError`
- Syntax cleanup
- Prep for signer refactor
existing unit tests
> #trivial error serialization, request type check

- packages/wallet-sdk/src/sign/extension/ExtensionSigner.test.ts
- packages/wallet-sdk/src/sign/extension/ExtensionSigner.ts
- packages/wallet-sdk/src/sign/interface.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts
we don't need return value from handshake. it's not being used on provider. we only care if it was successful or not. Promise<void> should be enough
unit tests
> #trivial simplify handshake return value

- packages/wallet-sdk/package.json
- packages/wallet-sdk/src/sign/walletlink/relay/type/WalletLinkSession.ts
- packages/wallet-sdk/src/vendor-js/eth-eip712-util/index.js
- packages/wallet-sdk/src/vendor-js/eth-eip712-util/util.js
- packages/wallet-sdk/yarn.lock
This PR replaces keccak and sha.js with a smaller, audited and more secure `@noble/hashes`, thus removing 11 deps.
Before (15 deps):
After (4 deps):
All tests passed.
> replace sha.js and keccak with smaller and more secure @noble/hashes

- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/CoinbaseWalletSDK.ts
- packages/wallet-sdk/src/core/provider/interface.ts
- packages/wallet-sdk/src/index.ts
- packages/wallet-sdk/src/sign/scw/SCWKeyManager.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/sign/util.ts
- packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.test.ts
- packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts
- packages/wallet-sdk/src/sign/walletlink/relay/WalletLinkRelay.test.ts
- packages/wallet-sdk/src/sign/walletlink/relay/WalletLinkRelay.ts
- packages/wallet-sdk/src/sign/walletlink/relay/connection/WalletLinkConnection.test.ts
- packages/wallet-sdk/src/sign/walletlink/relay/type/WalletLinkSession.ts
- packages/wallet-sdk/src/util/BaseStorage.test.ts
- packages/wallet-sdk/src/util/BaseStorage.ts
- packages/wallet-sdk/src/util/ScopedLocalStorage.test.ts
- packages/wallet-sdk/src/util/ScopedLocalStorage.ts
- packages/wallet-sdk/src/util/ScopedStorage.test.ts
- packages/wallet-sdk/src/util/ScopedStorage.ts
- packages/wallet-sdk/src/util/web.test.ts
* Allow consumer dapp to pass in a custom `BaseStorage` object, which will be used by the SDK internally
* Creates `browserStorageAdapter` and `mmkvStorageAdapter` helper functions which can be used to transform `localStorage` or React Native MMKV storage objects into a `BaseStorage`
* Renames `ScopedLocalStorage` to `ScopedStorage`
Tested manually + unit tests
> Allow consumer to pass in storage object

- packages/wallet-sdk/jest.config.ts
- packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/sign/interface.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.test.ts
- packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts
- packages/wallet-sdk/src/util/provider.test.ts
- packages/wallet-sdk/src/util/provider.ts
- Remove `accounts` and `chain` from `Signer` interface
- Relocate local handling of `eth_requestAccounts` to each signer
- `checkErrorForInvalidRequest` to handle deprecated method error as well
- Revert WalletLink changes on https://github.com/coinbase/coinbase-wallet-sdk/pull/1343
unit tests
> Simplify Signer state sync

- packages/wallet-sdk/src/CoinbaseWalletSDK.native.ts
Appends the SDK path to the appDeeplinkUrl instead of replacing the path
> Append SDK path to appDeeplinkUrl

- packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
found an issue caused by disconnect not able to reset completely
Manually + Unit Tests
> Disconnect to reset state completely

- packages/wallet-sdk/src/core/type/util.test.ts
- packages/wallet-sdk/src/core/type/util.ts
- packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.test.ts
- packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts
- packages/wallet-sdk/src/sign/walletlink/relay/WalletLinkRelay.ts
- packages/wallet-sdk/src/sign/walletlink/relay/mocks/relay.ts
- reduce call stack to process `eth_ecRecover` and `personal_ecRecover`
- deprecate `Relay.ethereumAddressFromSignedMessage`
unit tests
> [WL cleanup] simplify ecRecover requests handling

- packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.test.ts
- packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts
- packages/wallet-sdk/src/sign/walletlink/relay/WalletLinkRelay.ts
- packages/wallet-sdk/src/sign/walletlink/relay/mocks/relay.ts
- consolidate `signTypedData_*` handling
- update `personalSign` handling for consistency
- deprecate `Relay.signEthereumMessage`
- rewrite unit tests
unit tests
> [WL cleanup] simpify sign_typedData/personal_sign

- packages/wallet-sdk/package.json
- packages/wallet-sdk/src/sign/walletlink/relay/type/WalletLinkSession.ts
This [PR](https://github.com/coinbase/coinbase-wallet-sdk/pull/1376/files#diff-9a5f07fb15dec7abb885e5b6e61df8119ede8cb8e1cc456fa562cb91aefcc470R28) introduced a bug where  WalletLink session id's are incorrectly set to be 32 bytes, which is invalid.
This PR reverts the change and makes it 16 bytes
Tested manually
> Make WalletLink session id 16 bytes

- packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
3 new permission methods were introduced, they are 
* wallet_grantPermissions
* wallet_prepareCalls
* wallet_sendPreparedCalls
Allowing them in SCWSigner.
Unit Tests added
> Allowing Permission Methods in SDK

- packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/sign/util.ts
Adding the option for dapps to take users directly to Smart Wallet creation by passing a custom `scwOnboardMode` param to eth_requestAccounts
```
const [address] = await provider.request({ method: 'eth_requestAccounts', params: [{scwOnboardMode: 'create'}] })
```
unit tests & locally 
Create Button manual test
https://github.com/user-attachments/assets/20dc415c-eadb-4d3b-87ff-2e9b3cb741fe
Manual test of all 3 param possibilities 
https://github.com/user-attachments/assets/224280b5-fa68-450d-8813-23ed3717edaf
> add option to pass scwOnboardMode to eth_requestAccounts

- packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/sign/util.ts
This PR reverts the change from https://github.com/coinbase/coinbase-wallet-sdk/pull/1383 that adds non-standard parameters to eth_requestAccounts.
- These params seem misplaced and introduce complexity at the wrong abstraction layer.
- eth_requestAccounts should remain simple and align with standard usage.
This revert is intended to preserve the integrity of the basic request structure and to maintain alignment with standards that developers expect when integrating with our SDK.
Looking forward to hearing more context around this decision and any further discussions that can help clarify the intended direction. cc @nateReiners @spencerstock
> Revert #1383: Remove non-standard parameters from basic requests

- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/core/communicator/Communicator.test.ts
- packages/wallet-sdk/src/core/communicator/Communicator.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
- packages/wallet-sdk/src/sign/util.test.ts
This change initializes the communicator with the app metadata. This provides app metadata to the onboarding screen on keys.coinbase.com
Testing these changes requires running a few apps:
* Playground
* SCW.
1. build a version of the sdk and install it into the playground. Make sure the playground is using the newly built version
2. run the playground and scw locally (place a log where the communicator is initialized)
3. Check the message event from the sdks communicator and validate appName, and appLogoUrl are available inside of scw.
> Update Communicator to include app metadata

- packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/core/message/RPCMessage.ts
- packages/wallet-sdk/src/sign/interface.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/sign/util.test.ts
- packages/wallet-sdk/src/sign/util.ts
**What**
- This PR makes a change to pass raw request args to our signer selection and handshake methods
**Why**
- To enable smart wallet onboarding optimization through the passing of request params
Locally
Unit Tests
> Pass raw request args to handshake

- packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.test.ts
- packages/wallet-sdk/src/vendor-js/eth-eip712-util/index.js
- packages/wallet-sdk/src/vendor-js/eth-eip712-util/util.js
This PR https://github.com/coinbase/coinbase-wallet-sdk/pull/1336 removed sha.js and keccak/js in in favor of @noble/hashes but implemented the keccak256 hash incorrectly. This resulted in EIP712 messages failing for walletlink.
This fixes the change by using the functions how theyre intended to be used.
1. Create a local build (`cd ./packages/wallet-sdk && rm -rf dist && yarn build && cd ../../`) 
2. Start the dev server from root (`yarn dev`)
3. Open up the playground `localhost:3000`
4. Connect to the playground using walletlink
5. Test signed typed data v3 and v4 and ensure you're able to sign on mobile (Note v1 doesn't work on sdk v4.0.4 either)
> fix noble hash keccak256 usage

- examples/testapp/package.json
- examples/testapp/src/components/Layout.tsx
- examples/testapp/src/context/CBWSDKReactContextProvider.tsx
- yarn.lock
This PR renames the internals of the test app to point to HEAD (current master), Latest (current published version), and the previous v3 versions.
* Pull down the repo and start the dev server `yarn dev`
* Test HEAD and Latest. Should be the same version of the SDK
> Update testapp to use sdk latest

- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/core/provider/interface.ts
This PR extends the preferences object to support any config value. This PR also exposes new methods to get the provider or an new sdk object. 
Manually. In a follow up PR there will be an update to the test app to use the new create SDK object
> add support for any config parameter

- packages/wallet-sdk/src/CoinbaseWalletSDK.ts
- packages/wallet-sdk/src/createCoinbaseWalletProvider.test.ts
- packages/wallet-sdk/src/createCoinbaseWalletProvider.ts
- packages/wallet-sdk/src/createCoinbaseWalletSDK.test.ts
- packages/wallet-sdk/src/createCoinbaseWalletSDK.ts
- packages/wallet-sdk/src/index.ts
This PR adds two new utilities to interact with the SDK and Provider.
This PR also adds a deprecation notice on the SDK class
```tsx
createCoinabseWalletSDK
```
```tsx
createCoinbaseWalletProvider
```
These can be tested by building a local version of the SDK. Importing the SDK into a new project or the playground. Then instantiating the provider and interacting with it.
See this PR for usage https://github.com/coinbase/coinbase-wallet-sdk/pull/1404
> Add new utils to interact with the SDK and provider

- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/sign/util.test.ts
- packages/wallet-sdk/src/sign/util.ts
This fixes a bug where the first 'chainChanged' was not being emitted because no emitter callback was being passed to the WalletLinkSigner created by `listenForWalletLinkSessionRequest` 
Locally 
Here's a video showing the bug in 4.1.0 and this fix in HEAD
https://github.com/user-attachments/assets/e762a9d1-69f1-4124-a844-cf0dc346e9df
> Fix chainChanged event emitting for walletlink connection

- packages/wallet-sdk/src/core/type/util.ts
- Our favicon fetching script worked sometimes, but in other cases where sites did not add a favicon via a <link> tag, the favicon was not found and null was returned. 
- This changes the script to guess the favicon url based on convention
- The frontend handles malformed urls just in case
Locally
> Improve favicon fetching by guessing favicon url based on convention

- examples/testapp/next.config.js
- packages/wallet-sdk/src/CoinbaseWalletSDK.test.ts
- packages/wallet-sdk/src/CoinbaseWalletSDK.ts
- packages/wallet-sdk/src/createCoinbaseWalletSDK.test.ts
- packages/wallet-sdk/src/createCoinbaseWalletSDK.ts
- packages/wallet-sdk/src/util/crossOriginOpenerPolicy.test.ts
- packages/wallet-sdk/src/util/crossOriginOpenerPolicy.ts
Add additional coop warning for developers. This is meant to help resolve coop issues
1. Spin up the playground
2. Set the next.config.js COOP header to same-origin
3. Verify the warning is present inside the console when running the app.
4. You'll know the coop is properly set if you see the coop warning when interacting with the popup
https://github.com/user-attachments/assets/c5440e3c-20b5-4d50-be22-cfd111b06d73
> Add coop warning

- examples/testapp/config/headers.js
- examples/testapp/next.config.js
- examples/testapp/tsconfig.json
Remove the next.config headers for the SDK playground
Manually. SDK playground should load normally
> Disable next config headers

- examples/testapp/src/components/SDKConfig/SDKConfig.tsx
- packages/wallet-sdk/src/CoinbaseWalletSDK.ts
- packages/wallet-sdk/src/core/provider/interface.ts
- packages/wallet-sdk/src/createCoinbaseWalletSDK.ts
- packages/wallet-sdk/src/util/validatePreferences.test.ts
- packages/wallet-sdk/src/util/validatePreferences.ts
* Update the attribution property
* Adds support for auto attribution
* Removes support post onboarding flows (pending some design changes)
Using the SDK playground config page.
* To verify start the sdk playground. 
* Add a log to test options passed to the SDK
* Verify the keys and values for the attribution object
> Update the attribution property

- .github/workflows/main.yml
- examples/testapp/.eslintrc.js
- examples/testapp/src/components/Layout.tsx
- examples/testapp/src/components/MethodsSection/MethodsSection.tsx
- examples/testapp/src/components/RpcMethods/RpcMethodCard.tsx
- examples/testapp/src/components/RpcMethods/method/signMessageMethods.ts
- examples/testapp/src/components/SDKConfig/SDKConfig.tsx
- examples/testapp/src/context/CBWSDKReactContextProvider.tsx
- examples/testapp/src/pages/index.tsx
> trivial - add linting to playground

- examples/testapp/src/components/RpcMethods/RpcMethodCard.tsx
Param boxes are unwieldy. This gives them some ability to resize.
manually
https://github.com/user-attachments/assets/0effe7f0-295b-42a4-8eb9-b5bdb891d2e4
> Make playground params expand when needed

- examples/testapp/src/components/RpcMethods/RpcMethodCard.tsx
Added a copy button next to any example button that provides a message (so for all sign message RPCs)
https://github.com/user-attachments/assets/6193e458-ad83-49cd-8c7d-95b83c176bd0
> Add copy button to message examples

- examples/testapp/src/components/RpcMethods/RpcMethodCard.tsx
- examples/testapp/src/components/RpcMethods/shortcut/signMessageShortcuts.ts
Adding an example message for grant permission
https://github.com/user-attachments/assets/693db7ba-6466-4401-b9e8-41ebb788c190
> Add grant permissions example message

- examples/testapp/src/components/RpcMethods/RpcMethodCard.tsx
remove enable call from playground from sdk playground submit call.
This was always firing and is not actually useful.
Manually.
Just use the sdk playground. There should be no functional changes to how things work.
> remove enable call from playground

- packages/wallet-sdk/src/util/provider.test.ts
- packages/wallet-sdk/src/util/provider.ts
extended the setAppInfo pattern to RN's in app browser provider. 
This is used to block EOA account to connect to smartWalletOnly app, and also enables adding data suffix in future RN smart wallet account
we are passing flattened params, including metadata and preference, this is for maximizing compatibility across App SDK version in case of future App SDK config structure change
Manually, demo attached in RN's PR
https://github.com/user-attachments/assets/debb56a9-22d3-4aef-9cc7-f7a08b14436e
> Passing SDK config params to injected provider

- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/sign/interface.ts
- packages/wallet-sdk/src/vendor-js/eth-eip712-util/util.cjs
At some point signer `request` was generic but was recently made to return `unknown`. 
Manually tested.
> Signer `request` should be generic for consumers

- packages/wallet-sdk/src/core/communicator/Communicator.test.ts
- packages/wallet-sdk/src/core/communicator/Communicator.ts
When connecting to the dapp browser with linkdrop pathname and query params did not persist. This includes the full location for keysdot to process
1. Start keysdot (See corresponding PR on keys side) and sdk playground.
2. Set the keys url to localhost
3. Using the sim (needs cbw mobile on it) or ngrok with actual device, open the playground in a browser window. (add some random query params)
4. Open the onboarding flow and select mobile. This should open in the dapp browser. Verify the query params persist.
> update sdk to pass location in postmessage

- packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.test.ts
- packages/wallet-sdk/src/sign/walletlink/WalletLinkSigner.ts
fix: default import from cjs files causing module resolution errors in webpack
Note: we should remove the vendor-js files in favor of viem or similar
1. start the sdk playground
2. connect with walletlink
3. test EIP712 functions 
---  Going the extra mile:
1. spin up an app with vite, webpack, your favorite bundler of choice
2. connect with walletlink
3. test EIP712 functions 
Everything should load correctly and all EIP712 functions should sign successfully.
> fix: default import from cjs files causing module resolution errors in webpack

- packages/wallet-sdk/package.json
- packages/wallet-sdk/src/sdk-info.ts
Vitest should be a dev dependency.
> chore: move vitest to devDependencies

- packages/wallet-sdk/src/sign/walletlink/relay/connection/WalletLinkConnection.ts
This PR adds the app's `window.location` to the WalletLink event. We already do this for the origin, but there's cases where Wallet needs the full path.
Tested manually and verified that adding the field doesn't cause issues with older versions of Wallet.
> Send app location in WalletLink request

- examples/testapp/src/components/RpcMethods/RpcMethodCard.tsx
- examples/testapp/src/components/RpcMethods/shortcut/const.ts
- examples/testapp/src/components/RpcMethods/shortcut/walletTxShortcuts.ts
This PR makes it so that the chainId passed in a wallet_sendCalls requests is the chainId that is connected
https://github.com/user-attachments/assets/fbc793be-828b-419c-88f8-3db8d0387aa3
> Dynamically update chainid for send calls requests

- examples/testapp/next-env.d.ts
- examples/testapp/next.config.mjs
- examples/testapp/package.json
Next 14 removed the `next export` command in favor of the `output: export` in the next.config file
Run `yarn build`. Should generate an `out` directory
> Fix SDK Playground Export

- .github/workflows/build-and-deploy.yml
- examples/testapp/package.json
Static deploys started failing after upgrading to Next.js 14+. This should fix the SDK Playground deploys
See https://github.com/vercel/next.js/discussions/33751
From the root run `yarn export`.
Validate the out director inside the sdk playground director and make sure it has a `.nojekyll` file inside the out dir
> Fix SDK Playground Deploys

- .github/workflows/build-and-deploy.yml
- examples/testapp/next.config.mjs
- examples/testapp/package.json
Fix export to account for basePath
From the root run `yarn deploy`
Validate there is an `out` directory inside the sdk playground directory. Make sure it has a `.nojekyll` file inside the out dir
> Fix export to account for basePath

- examples/testapp/src/components/RpcMethods/RpcMethodCard.tsx
- `data` was being passed into `verify`  instead of `dataToSubmit` which is the mapped variable to translates ADDR_TO_FILL to the connected address.
Tested manually -- the "example message" action under the personal_sign section works without errors now after the fix
> fix: invalid params passed to personal_sign Example Message action

- examples/testapp/src/components/RpcMethods/RpcMethodCard.tsx
- examples/testapp/src/components/RpcMethods/method/ephemeralMethods.ts
- examples/testapp/src/components/RpcMethods/shortcut/ephemeralMethodShortcuts.ts
- examples/testapp/src/pages/index.tsx
- packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/core/constants.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
We used to see `eth_requestAccounts` as the handshake method, which does 2 things essentially:
- Authorizing the connection (by exchanging keys) and
- Returning the address
When exploring `wallet_sign`(`wallet_sendCalls`) and `wallet_connect`, the original idea was to merge another signing request with `eth_requestAccounts`, so we do 3 things at a time
- Authorizing the connection (by exchanging keys) and
- Returning the address
- Signing something
However, since the first request is for requesting trusted connection, the request itself is unencrypted. Hence, due to security reason, we couldn't request signing in this untrusted context.
This PR, is using @lukasrosario's idea, to create a `"Light Handshake"`, which will be used for establish a trusted communication channel, so subsequent …
> [BW-857] Abstract handshake into `coinbase_handshake`

- packages/wallet-sdk/src/CoinbaseWalletProvider.test.ts
- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
just renaming an internal RPC method
https://github.com/user-attachments/assets/6fe9363a-7ca1-43b9-addb-74b72cbd2662
> TRIVIAL - rename to handshake

- examples/testapp/src/components/RpcMethods/shortcut/signMessageShortcuts.ts
We expect a number, but the prior implementation is using the hex representation of chainId
Also updated to use the native token instead of an ERC20 since the ERC20 address is only applicable to a specific chain
Manually
> Update spend permission call to use eth and number for chainId

- .github/workflows/main.yml
- libs/crypto-key/.eslintrc.cjs
- libs/crypto-key/README.md
- libs/crypto-key/package.json
- libs/crypto-key/src/index.test.ts
- libs/crypto-key/src/index.ts
- libs/crypto-key/src/storage.test.ts
- libs/crypto-key/src/storage.ts
- libs/crypto-key/tsconfig.json
- libs/crypto-key/vitest.config.ts
- libs/crypto-key/vitest.setup.ts
- package.json
- yarn.lock
This PR adds a new lib called `crypto-key` which creates a new account for creating sub accounts.
Unit tests
> Create CryptoKey Lib for linked accounts

- .github/workflows/main.yml
- package.json
Merging the linked account work broke deploys because the crypto-key lib was not being built in CI
Manually
> fix deploy

- examples/testapp/src/components/RpcMethods/method/signMessageMethods.ts
Serialized responses are not being properly handled. This fix will parse out serialized responses during signature validation. I'd expect viem to do this internally but it does not.
Manually
Before
After
> Parse typed data response if it's a string

- examples/testapp/src/components/RpcMethods/method/connectionMethods.ts
- examples/testapp/src/components/RpcMethods/shortcut/connectionMethodShortcuts.ts
- examples/testapp/src/pages/index.page.tsx
- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/core/rpc/wallet_connect.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
This PR adds basic support for `wallet_connect`
To ensure requests are encrypted we use the handshake before sending the request to the popup. This ensures the request and response is encrypted. There may need to be modifications once landing the first round of support on the keys popup side
Manually
> ERC7846 `wallet_connect` Support

- examples/testapp/package.json
- examples/testapp/src/components/RpcMethods/RpcMethodCard.tsx
- libs/crypto-key/package.json
- packages/wallet-sdk/package.json
Because the --fix flag was always running during PR CI, it would never actually catch the lint issues.
Fix lint on master
> Fix lint on master

- examples/testapp/src/components/RpcMethods/method/walletTxMethods.ts
Parse the calls parameter either as a json or keep it as an object (parsing from the input text field turns it into a string)
Tried this calls request
With change:
Without change:
> Fix bug where wallet send calls wasn't able to parse the calls part of the request

- examples/testapp/src/components/RpcMethods/shortcut/connectionMethodShortcuts.ts
- packages/wallet-sdk/src/core/rpc/wallet_addAddress.ts
- packages/wallet-sdk/src/core/rpc/wallet_connect.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
This PR adds support for the getAppAccounts capability and improves sub-account handling logic.
Key changes:
* Added getAppAccounts shortcut in test app with chainId 84532
* Updated WalletConnectResponse type to handle getAppAccounts capability response as an array
* Modified SCWSigner to:
* Handle getAppAccounts capability responses
* Improve sub-account signer request routing logic
* Remove hardcoded ROOT_ACCOUNT_METHODS array
* Run the test app
* Connect wallet using WalletConnect
* Test the "Get App Accounts" shortcut
* Verify that sub-account handling works correctly when:
* Getting app accounts
* Switching between root and sub-accounts
* Making transactions from different accounts
* getAppAccounts capability now returns an array of AddAddressCapabilityResponse
* Sub-account signer …
> feat: Add getAppAccounts capability and improve sub-account handling

- packages/wallet-sdk/src/sign/scw/utils/getOwnerIndex.test.ts
- packages/wallet-sdk/src/sign/scw/utils/getOwnerIndex.ts
We were not padding 20 byte addresses when checking against the owner addresses. This fixes that
Manually and unit tests
> fix owner index lookup

- packages/wallet-sdk/src/vendor-js/eth-eip712-util/util.cjs
Adds missing `intToBuffer` method to https://github.com/coinbase/coinbase-wallet-sdk/blob/master/packages/wallet-sdk/src/vendor-js/eth-eip712-util/util.cjs#L106
> fix: missing methods vendor file

- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
The expected response for `wallet_addSubAccount` is `{address: string, factory?: string, factoryData?: string}`. However, after initially adding the wallet_addSubAccount and persisting it locally, the function only returns the address `string`. 
This PR updates the function to return the full subAccount object in the cache branch as expected.
Playground
> fix: incorrect return type for cached sub account

- packages/wallet-sdk/src/util/web.test.ts
- packages/wallet-sdk/src/util/web.ts
- When opening the popup, we append some necessary query params to the URL. Since the URL object is re-used, the query params were getting appended again on each popup open.
- This was fixed by adding a simple check for if the query param already exists
- Manually and unit tests
https://github.com/user-attachments/assets/b8d8313f-1bc3-462f-ab69-5f270047ae2b
https://github.com/user-attachments/assets/e612034b-0009-40b0-ae76-6b76e9874f1b
> fix: query params getting duplicated on each popup open

- examples/testapp/src/pages/index.page.tsx
Connected state was not triggered for injected wallets in mobile WebView because provider events are not being emitted. This change checks the `isCoinbaseBrowser` property on the provider and sets the connected state if it is present.
Loaded the playground in the coinbase mobile wallet browser and ensured the methods that depend on a wallet being connected were shown
> fix: injected wallet playground webview

- examples/testapp/src/pages/add-sub-account/components/AddSubAccount.tsx
- examples/testapp/src/pages/add-sub-account/components/SendCalls.tsx
- examples/testapp/src/pages/add-sub-account/index.page.tsx
- packages/wallet-sdk/src/core/rpc/wallet_prepareCalls.ts
- packages/wallet-sdk/src/core/rpc/wallet_sendPreparedCalls.ts
- packages/wallet-sdk/src/index.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/sign/scw/utils/createSubAccountSigner.test.ts
- packages/wallet-sdk/src/sign/scw/utils/createSubAccountSigner.ts
- packages/wallet-sdk/src/util/encoding.test.ts
- packages/wallet-sdk/src/util/encoding.ts
Replace wallet_sendCalls with wallet_prepareCalls + wallet_sendPreparedCalls
Tried Send Calls on playground and updated tests
> feat: prepare wallet rpcs

- examples/testapp/src/pages/add-sub-account/index.page.tsx
- examples/testapp/src/pages/import-sub-account/index.page.tsx
- examples/testapp/src/utils/unsafe_generateOrLoadPrivateKey.ts
Refactors private key generation and retrieval used in example app pages into a single function
https://github.com/coinbase/coinbase-wallet-sdk/pull/1554#discussion_r2010902683
Tested the add account and send calls flow in the sub accounts page in playground
> chore: refactor localstorage private key in example

- .github/workflows/release-canary.yml
Seeing this error when trying to publish
```
➤ YN0033: No authentication configured for request
➤ YN0000: Failed with errors in 0s 275ms
```
This PR updates the publish action to use npm  directly vs proxying through yarn
n/a
> Try using npm directly to publish

- packages/wallet-sdk/src/util/web.test.ts
- packages/wallet-sdk/src/util/web.ts
- Increased the popup height to 700 to match the new expected height on keys.coinbase.com
- Manually and unit tests
https://github.com/user-attachments/assets/0845ec16-c0c2-44df-838f-07a24c4f06d9
> Increase popup height

- packages/wallet-sdk/src/core/rpc/coinbase_fetchSpendPermissions.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/sign/scw/utils.test.ts
- packages/wallet-sdk/src/sign/scw/utils.ts
- packages/wallet-sdk/src/store/store.ts
This PR adds support for app to call `coinbase_fetchPermissions` directly with provider object.
A new shortcut added: if app is connected to user's sub account and universal account, they can omit the params field completely and have it filled by provider. 
| fetch w/o params in logged in state | fetch w params | fetch w/o params in logged out state |
| ---------- | ---------- | ---------- |
| <video src='https://github.com/user-attachments/assets/5cf81da0-3120-4dbb-b931-3ef3f54f4aae' /> | <video src='https://github.com/user-attachments/assets/b9997742-05bd-491e-b9ad-21f4857404ed' /> | <video src='https://github.com/user-attachments/assets/97f0dc7a-cdaa-4c02-aba4-4c1dc867ff72' /> |
Cache in zustand
> [BW-1540] Add Support for Fetching Spend Limits via Provider 

- examples/testapp/src/context/ConfigContextProvider.tsx
- examples/testapp/src/pages/auto-sub-account/index.page.tsx
- packages/wallet-sdk/src/CoinbaseWalletProvider.ts
- packages/wallet-sdk/src/core/provider/interface.ts
- packages/wallet-sdk/src/core/rpc/coinbase_fetchSpendPermissions.ts
- packages/wallet-sdk/src/core/rpc/wallet_connect.ts
- packages/wallet-sdk/src/createCoinbaseWalletSDK.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/sign/scw/utils.ts
- packages/wallet-sdk/src/store/store.ts
This PR adds support for spend limits in WalletConnect requests and responses. The changes include:
- Added new types `SpendLimitsCapabilityRequest` and `SpendLimitsCapabilityResponse` to handle spend limit functionality
- Added `GetSpendLimitsCapabilityRequest` and `GetSpendLimitsCapabilityResponse` for retrieving spend limits
- Updated `WalletConnectRequest` and `WalletConnectResponse` types to include spend limit capabilities
- Added proper error handling for spend limit responses using `SerializedEthereumRpcError`
- Verified type definitions compile correctly with TypeScript
- Tested spend limit capability integration with existing WalletConnect flow
- Ensured error handling works as expected for spend limit responses****
> [BW-1655] Add support for auto spend limits via config

- packages/wallet-sdk/src/core/provider/interface.ts
- packages/wallet-sdk/src/createCoinbaseWalletSDK.ts
- packages/wallet-sdk/src/sign/scw/utils.test.ts
- packages/wallet-sdk/src/sign/scw/utils.ts
- packages/wallet-sdk/src/sign/scw/utils/createSubAccountSigner.test.ts
- packages/wallet-sdk/src/sign/scw/utils/createSubAccountSigner.ts
- packages/wallet-sdk/src/sign/scw/utils/handleInsufficientBalance.ts
- packages/wallet-sdk/src/store/store.ts
- Added `paymasterUrls` in the `createCoinbaseWalletSDK` config.
- Updated `createWalletSendCallsRequest` to accept `calls` and `capabilities`
- Updated `createWalletSendCallsRequest` to inject paymaster urls
Added tests
> feat: paymaster urls in config

- examples/testapp/src/pages/auto-sub-account/index.page.tsx
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/sign/scw/utils.ts
- packages/wallet-sdk/src/sign/scw/utils/createSubAccountSigner.test.ts
- packages/wallet-sdk/src/sign/scw/utils/createSubAccountSigner.ts
- Adds data suffix support via `wallet_prepareCalls` to createSubAccountSigner
- Manual testing
- Unit tests
> feat: sub accounts data suffix support

- examples/testapp/src/components/EventListeners/EventListenersCard.tsx
- examples/testapp/src/hooks/useEventListeners.test.tsx
- examples/testapp/src/hooks/useEventListeners.tsx
This PR updates the SDK Playground to use EIP1193 defined events: `on` and `removeListener`.
Manually
> Udpate the SDK Playground to use EIP1193 defined events

- examples/testapp/src/components/RpcMethods/shortcut/connectionMethodShortcuts.ts
- packages/wallet-sdk/src/createCoinbaseWalletSDK.test.ts
- packages/wallet-sdk/src/createCoinbaseWalletSDK.ts
Fixes a typo in the SDK helper utility method for fetching sub accounts.
Manually
> fix typo in getSubAccounts

- packages/wallet-sdk/src/sign/scw/utils.ts
Updates the message in the insufficient balance toast for dynamic spend limits to refer to spend limits instead of spend pemissions.
> fix: update message in dynamic spend limits insufficient balance toast

- examples/testapp/src/components/Layout.tsx
- examples/testapp/src/components/RpcMethods/shortcut/connectionMethodShortcuts.ts
- examples/testapp/src/context/ConfigContextProvider.tsx
- examples/testapp/src/pages/add-sub-account/components/AddSubAccount.tsx
- examples/testapp/src/pages/add-sub-account/components/GrantSpendPermission.tsx
- examples/testapp/src/pages/add-sub-account/index.page.tsx
- examples/testapp/src/pages/auto-sub-account/index.page.tsx
- packages/wallet-sdk/src/core/rpc/wallet_addSubAccount.ts
- packages/wallet-sdk/src/core/rpc/wallet_connect.ts
- packages/wallet-sdk/src/createCoinbaseWalletSDK.test.ts
- packages/wallet-sdk/src/createCoinbaseWalletSDK.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/sign/scw/utils.test.ts
- packages/wallet-sdk/src/sign/scw/utils.ts
- Updates SDK to conform to updates to ERC PR https://github.com/jakeFeldman/ERCs/pull/1
- Fixes default spend limits to be injected on `wallet_connect` if `addSubAccount` is present
- Makes keys param in `wallet_addSubAccount` optional
- Updated tests
- Manual testing on playground
> chore: update sub accounts rpcs to match updated spec

- packages/wallet-sdk/src/core/rpc/coinbase_fetchSpendPermissions.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/sign/scw/utils.test.ts
- packages/wallet-sdk/src/sign/scw/utils.ts
- packages/wallet-sdk/src/store/store.ts
Caches the wallet_connect response to be returned on subsequent wallet_connect calls. This cache is cleared on disconnect.
Unit tests and manual testing
> fix: return cached wallet_connect response

- examples/testapp/src/pages/auto-sub-account/index.page.tsx
- packages/wallet-sdk/src/core/provider/interface.ts
- packages/wallet-sdk/src/createCoinbaseWalletSDK.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- Removes the `dynamicSpendLimit` config option and enables it by default for sub accounts
- Also removes the restriction that only enables it when auto sub accounts is enabled
Manual testing, unit tests
> fix: remove dynamic spend limit configuration from sdk constructor

- examples/testapp/src/pages/add-sub-account/components/PersonalSign.tsx
- examples/testapp/src/pages/auto-sub-account/index.page.tsx
- packages/wallet-sdk/src/sign/scw/utils/createSubAccountSigner.test.ts
- packages/wallet-sdk/src/sign/scw/utils/createSubAccountSigner.ts
Sub account was incorrectly passing hex-encoded data to `signMessage`. This was fixed by decoding the message param first before passing to be signed by the account.
Tests were added to check for this and playground now shows signature validation result.
Unit tests, manual testing
> fix: sub account personal_sign message encoding

- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
`wallet_connect` params are empty on `eth_requestAccounts` when `enableAutoSubAccounts` is true. This is because we were using a stale sub account config after calling `initSubAccountConfig`. The bug is resolved by calling the sub account config from the store after calling `initSubAccountConfig`.
Manual testing
> fix: usage of stale sub account config

- examples/testapp/src/pages/add-sub-account/components/AddSubAccountWithoutKeys.tsx
- examples/testapp/src/pages/add-sub-account/index.page.tsx
- packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
Fixed the population of the `account.keys` field if not present in `wallet_addSubAccount` params
Manual testing – updated playground
Fixed tests to be more comprehensive
> fix: wallet_addSubAccount keys population if not provided

- examples/testapp/src/pages/auto-sub-account/index.page.tsx
- packages/wallet-sdk/src/core/provider/interface.ts
- packages/wallet-sdk/src/core/rpc/coinbase_fetchSpendPermissions.ts
- packages/wallet-sdk/src/core/rpc/wallet_connect.ts
- packages/wallet-sdk/src/createCoinbaseWalletSDK.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/sign/scw/utils.test.ts
- packages/wallet-sdk/src/sign/scw/utils.ts
- packages/wallet-sdk/src/store/store.ts
renaming spend limits back to spend permissions
Unit tests, playground with updated CBSW wallet
> refactor: rename spend limit back to spend permission

- examples/testapp/src/pages/auto-sub-account/index.page.tsx
- packages/wallet-sdk/src/core/provider/interface.ts
- packages/wallet-sdk/src/createCoinbaseWalletSDK.ts
- packages/wallet-sdk/src/sign/scw/utils.test.ts
- packages/wallet-sdk/src/sign/scw/utils.ts
Removes sub account `defaultSpendPermission` config option
Ensured all unit tests pass
> chore: remove default spend limits

- examples/testapp/src/pages/auto-sub-account/index.page.tsx
- packages/wallet-sdk/src/sign/scw/SCWSigner.test.ts
- packages/wallet-sdk/src/sign/scw/SCWSigner.ts
- packages/wallet-sdk/src/sign/scw/utils.test.ts
- packages/wallet-sdk/src/sign/scw/utils.ts
https://linear.app/coinbase/issue/BA-2376/sdk-update-default-sub-account-behavior
When `enableAutoSubAccounts` is false, we no longer automatically make the sub account the 'active' account. All requests meant for the sub accounts need to explicitly specify the sub account address.
In this mode, the sub account is always returned at index 1 when calling `eth_requestAccounts` and `eth_accounts`.
Unit tests, manual testing in playground
> fix: update manual sub account odering behavior
